(function(){
'use strict';
const STORAGE_KEY='travelClaimsManagerStateV2';
const COOKIE_KEY='travelClaimsManagerVersion';
const CACHE_NAME='travel-claims-manager-state-v2';
const BASES={DPOW:{name:'DPOW',postcode:'DN33 2BA'},SGH:{name:'SGH',postcode:'DN15 7BH'}};
const BAKED_WORKER_URL='https://travel-claims-ics.n-e-alwaa.workers.dev';
const DEFAULT_STATE={settings:{fullName:'',baseSite:'DPOW',designation:'',personalNumber:'',homeAddress:'',vehicleReg:'',engineCc:'',claimableMiles:'',passengerMiles:'',commuteMinutes:30,mileageRate:0.30,commuteType:'none',commuteCost:'',commuteCostLabel:'Humber toll'},icsUrl:'',workerUrl:BAKED_WORKER_URL,events:[],selectedMonths:[],manualEvents:[],claims:{},expenseLog:[],activeMonth:'',signature:null,signatureDate:''};
function clone(o){return JSON.parse(JSON.stringify(o));}
let state=loadState();let saveTimer;let deferredInstallPrompt=null;
const $=id=>document.getElementById(id),qsa=s=>Array.from(document.querySelectorAll(s));
function mergeState(saved){const base=clone(DEFAULT_STATE);if(!saved||typeof saved!=='object')return base;return {...base,...saved,workerUrl:BAKED_WORKER_URL,settings:{...base.settings,...(saved.settings||{})},claims:saved.claims||{},events:Array.isArray(saved.events)?saved.events:[],manualEvents:Array.isArray(saved.manualEvents)?saved.manualEvents:[],selectedMonths:Array.isArray(saved.selectedMonths)?saved.selectedMonths:[],expenseLog:Array.isArray(saved.expenseLog)?saved.expenseLog:[]};}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)return mergeState(JSON.parse(raw));}catch(e){}try{const raw=localStorage.getItem('travelClaimsManagerStateV1');if(raw)return mergeState(JSON.parse(raw));}catch(e){}return clone(DEFAULT_STATE);}
async function recoverFromCache(){try{if(localStorage.getItem(STORAGE_KEY)||!window.caches)return;const c=await caches.open(CACHE_NAME);const r=await c.match(new Request(location.origin+'/__travel_claims_state__'));if(r){state=mergeState(await r.json());bindSettings(true);renderAll();showToast('Recovered your latest local draft.');}}catch(e){}}
function saveState(){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{const serial=JSON.stringify(state);localStorage.setItem(STORAGE_KEY,serial);document.cookie=COOKIE_KEY+'=2; max-age=31536000; samesite=lax; path=/';if(window.caches&&location.protocol!=='file:'){const c=await caches.open(CACHE_NAME);await c.put(new Request(location.origin+'/__travel_claims_state__'),new Response(serial,{headers:{'Content-Type':'application/json'}}));}$('saveStatus').textContent='Saved locally · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}catch(e){$('saveStatus').textContent='Local save warning';}},150);}
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2600);}
const VALID_TABS=['setup','shifts','claim','log'];
function switchTab(name){if(!VALID_TABS.includes(name))name='setup';if(name!=='setup'&&requiredSetupMissing().length){name='setup';if(location.hash!=='#setup')history.replaceState(null,'','#setup');}qsa('.tab').forEach(b=>{const active=b.dataset.tab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));});qsa('.panel').forEach(p=>{const active=p.id===name;p.classList.toggle('active',active);p.hidden=!active;});if(name==='claim'){prepareSelectedClaims();renderClaimMonthOptions();}if(name==='shifts')setTimeout(()=>loadIcs(true),0);if(name==='log')renderExpenseLog();}
function navigate(name){if(!VALID_TABS.includes(name))return;if(name!=='setup'&&!validateSetup()){switchTab('setup');location.hash='setup';return}if(location.hash.slice(1)!==name)location.hash=name;else switchTab(name);window.scrollTo({top:0,behavior:'smooth'});}
qsa('.tab').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();navigate(b.dataset.tab);}));
$('setupContinue').addEventListener('click',e=>{e.preventDefault();if(validateSetup())navigate('shifts');});
window.addEventListener('hashchange',()=>switchTab(location.hash.slice(1)||'setup'));
function updateWorkflowHints(){
  const hint=$('shiftsContinueHint');
  if(hint) hint.textContent=state.selectedMonths.length?`${state.selectedMonths.length} month${state.selectedMonths.length===1?'':'s'} selected.`:'Select at least one claim month first.';
  const feedback=$('exportFeedback');
  if(feedback&&state.activeMonth){const c=state.claims[state.activeMonth];feedback.textContent=c?.exportedAt?`Signed PDF saved for ${monthLabel(state.activeMonth)} and added to the Expense Log.`:'Review this month, then use “Sign and save PDF”.';feedback.className=c?.exportedAt?'calendar-feedback success subtle':'calendar-feedback subtle';}
  const hs=$('humberBridge'); if(hs) hs.disabled=state.settings.commuteType!=='toll';
  const ss=$('setupSignatureStatus'); if(ss) ss.textContent=state.signature?'Signature saved locally ✓':'No signature saved';
}
function requiredSetupMissing(){const fields=[['fullName','Full name'],['baseSite','Base site'],['designation','Designation / job title'],['personalNumber','Personal number'],['homeAddress','Home address'],['vehicleReg','Vehicle registration'],['engineCc','Engine cc'],['claimableMiles','Claimable miles per one-way journey'],['commuteMinutes','Average commute time to work']];const missing=fields.filter(([id])=>!String($(id).value??'').trim()).map(x=>x[1]);if(!state.signature)missing.push('Sample signature');return missing;}
function validateSetup(){const missing=requiredSetupMissing();if(missing.length){showToast('Complete the required Setup fields first.');alert('Please complete the following required Setup items before continuing:\n\n• '+missing.join('\n• '));return false}const digits=String($('personalNumber').value||'').replace(/\D/g,'');if(digits.length<8){alert('Personal number must contain at least 8 digits.');return false}return true;}
$('shiftsContinue').addEventListener('click',e=>{e.preventDefault();if(!state.selectedMonths.length){showToast('Select at least one claim month first.');$('shiftsContinueHint').textContent='Select at least one claim month first.';return}state.activeMonth=state.selectedMonths.slice().sort()[0];renderClaimMonthOptions();generateClaim(false);saveState();navigate('claim');});
$('claimContinue').addEventListener('click',e=>{e.preventDefault();if(!state.activeMonth||!state.claims[state.activeMonth]){showToast('Generate a claim first.');return}navigate('log');});
function monthKey(date){const d=new Date(date);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');}
function monthLabel(key){const [y,m]=key.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString(undefined,{month:'long',year:'numeric'});}
function fmtDateTime(dt){const d=new Date(dt);return d.toLocaleDateString(undefined,{day:'2-digit',month:'2-digit'})+' '+d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}
function displayDate(d){const x=new Date(d);return String(x.getDate()).padStart(2,'0')+'/'+String(x.getMonth()+1).padStart(2,'0');}
function parseTimeFromDate(d){return new Date(d).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',hour12:false});}
function addMinutes(d,n){return new Date(new Date(d).getTime()+n*60000);}
function num(v){return Number(v)||0;}function fmtNum(v){const n=Number(v);return n?String(Number(n.toFixed(1))):'';}function money(v){const n=Number(v)||0;return n?'£'+n.toFixed(2):'';}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;');}
function getPostcode(addr){const m=String(addr||'').match(/[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}/i);return m?m[0].toUpperCase():String(addr||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean).slice(-1)[0]||'';}
function formatPersonalNumber(v){const raw=String(v||'').trim();const digits=raw.replace(/\D/g,'');if(digits.length<8)return raw;const first=digits.slice(0,8).match(/.{1,2}/g).join('/');const extra=digits.slice(8);return first+(extra?'-'+extra:'');}
function formatAddressLines(v){let parts=String(v||'').split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean);if(!parts.length)return [];const pc=getPostcode(v);if(pc){parts=parts.map(x=>x.replace(new RegExp(pc.replace(' ','\\s*'),'i'),'').trim()).filter(Boolean);parts.push(pc);}return parts.slice(0,5);}
function bindSettings(rebind=false){
  const ids=['fullName','baseSite','designation','personalNumber','homeAddress','vehicleReg','engineCc','claimableMiles','passengerMiles','commuteMinutes','mileageRate','commuteType','commuteCost','commuteCostLabel'];
  ids.forEach(id=>{const el=$(id);el.value=state.settings[id]??'';if(!rebind&&!el.dataset.bound){const save=()=>{state.settings[id]=el.value;updateWorkflowHints();saveState();};el.addEventListener('input',save);el.addEventListener('change',save);el.dataset.bound='1';}});
  $('icsUrl').value=state.icsUrl||'';state.workerUrl=BAKED_WORKER_URL;
  {const el=$('icsUrl');if(!rebind&&!el.dataset.bound){const save=()=>{state.icsUrl=el.value.trim();saveState();};el.addEventListener('input',save);el.addEventListener('change',save);el.dataset.bound='1';}}
}
function normalizeUrl(url){let u=String(url||'').trim();if(u.startsWith('webcal://'))u='https://'+u.slice(9);return u;}
function unfoldICS(text){const lines=text.replace(/\r\n/g,'\n').replace(/\r/g,'\n').split('\n');const out=[];for(const line of lines){if(/^[ \t]/.test(line)&&out.length)out[out.length-1]+=line.slice(1);else out.push(line);}return out;}
function unescapeText(s){return String(s??'').replace(/\\n/g,'\n').replace(/\\,/g,',').replace(/\\;/g,';').replace(/\\\\/g,'\\');}
function icsDate(v){if(!v)return null;let s=String(v).replace(/^.*?:/,'');if(/^\d{8}$/.test(s))return new Date(Number(s.slice(0,4)),Number(s.slice(4,6))-1,Number(s.slice(6,8)),9,0,0);const z=s.endsWith('Z');if(z)s=s.slice(0,-1);const y=+s.slice(0,4),mo=+s.slice(4,6)-1,d=+s.slice(6,8),h=+(s.slice(9,11)||0),mi=+(s.slice(11,13)||0),sec=+(s.slice(13,15)||0);return z?new Date(Date.UTC(y,mo,d,h,mi,sec)):new Date(y,mo,d,h,mi,sec);}
function parseCalendarFallback(text){const lines=unfoldICS(text),events=[];let cur=null;for(const line of lines){if(line==='BEGIN:VEVENT'){cur={};continue}if(line==='END:VEVENT'){if(cur?.dtstart)events.push(cur);cur=null;continue}if(!cur)continue;const m=line.match(/^([A-Z0-9-]+)(?:;[^:]*)?:(.*)$/);if(m)cur[m[1].toLowerCase()]=m[2];}
return expandSimpleRecurrence(events.map((e,i)=>({uid:e.uid||'fallback-'+i,summary:unescapeText(e.summary||'Shift'),description:unescapeText(e.description||''),start:icsDate(e.dtstart),end:icsDate(e.dtend||e.dtstart),allDay:(e.dtstart||'').length===8,rrule:e.rrule||'',exdate:e.exdate||''})).filter(e=>e.start));}
function expandSimpleRecurrence(events){const out=[];const limit=new Date(Date.now()+1000*60*60*24*366*3);for(const e of events){const duration=(e.end?.getTime()||e.start.getTime()+3600000)-e.start.getTime();const rule=e.rrule||'';if(!rule){out.push(e);continue}const parts={};rule.split(';').forEach(x=>{const [k,v]=x.split('=');parts[k]=v});const freq=parts.FREQ;let interval=Number(parts.INTERVAL||1),count=Number(parts.COUNT||0),until=parts.UNTIL?icsDate(parts.UNTIL):null;let cur=new Date(e.start),n=0;while(cur<=limit&&(until?cur<=until:true)&&(count? n<count:true)){out.push({...e,uid:e.uid+'-'+n,start:new Date(cur),end:new Date(cur.getTime()+duration)});n++;if(freq==='DAILY')cur.setDate(cur.getDate()+interval);else if(freq==='WEEKLY')cur.setDate(cur.getDate()+7*interval);else if(freq==='MONTHLY')cur.setMonth(cur.getMonth()+interval);else break} }return out;}
function classifyEvent(e){const s=(e.summary+' '+(e.description||'')).toLowerCase();if(/study|\bsdt\b/.test(s))return {status:'Do not claim',category:'study'};if(/leave|annual|holiday|a\/l|maternity|mat\s*-?leave|bereav|sick|sickness|strike|\bphc\b|healthcare|appointment/.test(s))return {status:'Do not claim',category:'leave'};return {status:'Claim',category:'work'};}
async function fetchWithTimeout(url,ms=15000,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',redirect:'error',signal:c.signal,...init});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text();}finally{clearTimeout(timer);}}
function isIcs(text){return /BEGIN:VCALENDAR/i.test(text)&&/BEGIN:VEVENT/i.test(text);}
async function fetchText(url){const u=normalizeUrl(url);let last=null;try{const text=await fetchWithTimeout(BAKED_WORKER_URL.replace(/\/+$/,'')+'/ics',15000,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:u})});if(isIcs(text))return {text,source:'Travel Claims secure Worker'};last=new Error('Worker returned a response that was not an ICS calendar.');}catch(e){last=e;}try{const text=await fetchWithTimeout(u);if(isIcs(text))return {text,source:'Direct calendar'};last=new Error('Direct calendar response was not ICS.');}catch(e){last=e;}throw last||new Error('Unable to fetch calendar. You can import an .ics file instead.');}
function claimWindowMonths(){const out=[],now=new Date();for(let i=3;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);out.push(monthKey(d));}return out;}
function eventFingerprint(e){return [e.summary||'',new Date(e.start).toISOString(),new Date(e.end||e.start).toISOString()].join('|');}
function applyCalendarText(text,source){const parsed=parseCalendarFallback(text);if(!parsed.length)throw new Error('No calendar events were found.');const oldByUid=new Map(state.events.map(e=>[e.uid,e]));const next=parsed.map((e,i)=>{const c=classifyEvent(e),old=oldByUid.get(e.uid);return {...e,id:e.uid+'-'+i,status:old?.status||c.status,category:c.category,source};});const nextByUid=new Map(next.map(e=>[e.uid,e]));let added=0,removed=0,changed=0;for(const [uid,e] of nextByUid){const old=oldByUid.get(uid);if(!old)added++;else if(eventFingerprint(old)!==eventFingerprint(e))changed++;}for(const uid of oldByUid.keys())if(!nextByUid.has(uid))removed++;state.events=next;const allowed=new Set(claimWindowMonths());state.selectedMonths=state.selectedMonths.filter(m=>allowed.has(m));renderAll();saveState();return {added,removed,changed};}
let calendarLoading=false;
async function loadIcs(automatic=false){if(calendarLoading)return;state.icsUrl=$('icsUrl').value.trim();state.workerUrl=BAKED_WORKER_URL;saveState();const feedback=$('calendarFeedback');if(!state.icsUrl){feedback.className='calendar-feedback error';feedback.textContent='No ICS calendar URL is saved. Go back to Setup and paste your Allocate calendar link.';return}calendarLoading=true;$('icsState').textContent='Refreshing calendar…';feedback.className='calendar-feedback loading';feedback.textContent='Refreshing your saved calendar automatically…';try{const result=await fetchText(state.icsUrl);const diff=applyCalendarText(result.text,result.source);$('icsState').textContent=`${state.events.length} events loaded · ${result.source}`;const summary=[];if(diff.changed)summary.push(`${diff.changed} shift${diff.changed===1?'':'s'} changed`);if(diff.added)summary.push(`${diff.added} shift${diff.added===1?'':'s'} added`);if(diff.removed)summary.push(`${diff.removed} shift${diff.removed===1?'':'s'} removed`);feedback.className='calendar-feedback success';feedback.textContent=summary.length?`Calendar refreshed. ${summary.join(', ')}.`:'Calendar refreshed. No rota changes detected since the last fetch.';if(!automatic)showToast('Calendar refreshed.');}catch(e){const msg=e.name==='AbortError'?'Calendar request timed out.':(e.message||'Could not fetch calendar.');$('icsState').textContent='Calendar refresh failed';feedback.className='calendar-feedback error';feedback.textContent=`Automatic calendar refresh failed: ${msg} You can still import an .ics file directly below.`;}finally{calendarLoading=false;}}
async function loadIcsFile(file){if(!file)return;const feedback=$('calendarFeedback');feedback.className='calendar-feedback loading';feedback.textContent='Reading the ICS file locally…';try{const text=await file.text();if(!isIcs(text))throw new Error('The selected file does not look like an ICS calendar.');applyCalendarText(text,'Local file');$('icsState').textContent=state.events.length+' events loaded · Local file';feedback.className='calendar-feedback success';feedback.textContent=`ICS file imported successfully: ${state.events.length} events. Select the month(s) you want to claim, then press Continue to Claim Form.`;showToast('ICS file imported locally.');}catch(e){$('icsState').textContent='ICS file load failed';feedback.className='calendar-feedback error';feedback.textContent=e.message||'Could not read the ICS file.';showToast(e.message||'Could not read the ICS file.');}}
$('icsFile').addEventListener('change',e=>loadIcsFile(e.target.files[0]));
function allEventItems(){return [...state.events,...state.manualEvents];}
function renderMonths(){const months=claimWindowMonths();$('monthPicker').className='month-picker';$('monthPicker').innerHTML=months.map(m=>{const count=allEventItems().filter(e=>monthKey(e.start)===m).length;return `<label class="month-chip"><input type="checkbox" data-month="${m}" ${state.selectedMonths.includes(m)?'checked':''}>${monthLabel(m)}<span class="month-count">${count} imported shift${count===1?'':'s'}</span></label>`}).join('');qsa('#monthPicker input').forEach(i=>i.addEventListener('change',()=>{state.selectedMonths=qsa('#monthPicker input:checked').map(x=>x.dataset.month);renderClaimMonthOptions();renderShifts();updateWorkflowHints();saveState();}));updateWorkflowHints();}
function renderShifts(){const selected=new Set(state.selectedMonths);const items=allEventItems().filter(e=>selected.has(monthKey(e.start))).sort((a,b)=>new Date(a.start)-new Date(b.start));if(!state.selectedMonths.length){$('shiftList').className='shift-list empty';$('shiftList').textContent='Select a claim month above to display its imported shifts.';return}if(!items.length){$('shiftList').className='shift-list empty';$('shiftList').textContent='No imported shifts fall within the selected month(s).';return}$('shiftList').className='shift-list';$('shiftList').innerHTML=items.map(e=>{const date=fmtDateTime(e.start),end=e.end?fmtDateTime(e.end):'',cat=e.category||'work',status=e.status==='Claim'?'Claim':'Do not claim';return `<div class="shift shift-${cat} status-${status==='Claim'?'claim':'no-claim'} ${e.source==='manual'?'manual':''}" data-id="${escapeAttr(e.id)}"><div class="date">${date.split(' ')[0]}</div><div><div class="summary">${escapeHtml(e.summary||'Unscheduled travel')}</div><div class="times">${date.split(' ').slice(1).join(' ')}${end?' → '+end:''}</div></div><select class="shift-status"><option>Claim</option><option>Do not claim</option></select><button class="delete" title="Delete shift" aria-label="Delete shift">×</button></div>`}).join('');qsa('.shift').forEach(row=>{const id=row.dataset.id,item=allEventItems().find(x=>x.id===id),sel=row.querySelector('select');sel.value=item.status==='Claim'?'Claim':'Do not claim';sel.addEventListener('change',()=>{item.status=sel.value;row.classList.toggle('status-claim',sel.value==='Claim');row.classList.toggle('status-no-claim',sel.value!=='Claim');saveState();});row.querySelector('.delete').addEventListener('click',()=>{state.events=state.events.filter(x=>x.id!==id);state.manualEvents=state.manualEvents.filter(x=>x.id!==id);renderAll();saveState();});});}
$('selectAllMonths').addEventListener('click',()=>{state.selectedMonths=claimWindowMonths();renderAll();saveState();});$('clearMonths').addEventListener('click',()=>{state.selectedMonths=[];renderClaimMonthOptions();renderMonths();saveState();});
$('addManualShift').addEventListener('click',()=>{$('manualShiftForm').reset();$('manualDate').value=new Date().toISOString().slice(0,10);$('manualStart').value='09:00';$('manualEnd').value='17:00';$('manualShiftDialog').showModal();});qsa('[data-close-manual]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();$('manualShiftDialog').close();}));
$('manualShiftForm').addEventListener('submit',e=>{e.preventDefault();const date=$('manualDate').value,start=$('manualStart').value,end=$('manualEnd').value;if(!date||!start||!end)return;const s=new Date(date+'T'+start),en0=new Date(date+'T'+end),en=en0<=s?new Date(en0.getTime()+86400000):en0,id='manual-'+Date.now();state.manualEvents.push({id,uid:id,summary:$('manualReason').value.trim()||'Unscheduled work',description:'Manual travel',start:s.toISOString(),end:en.toISOString(),status:'Claim',category:'work',source:'manual'});state.selectedMonths=[...new Set([...state.selectedMonths,monthKey(s)])];$('manualShiftDialog').close();renderAll();saveState();showToast('Unscheduled day added.');});
function prepareSelectedClaims(){for(const key of state.selectedMonths){const previous=state.claims[key]||{};if(!previous.rows?.length)state.claims[key]={...previous,rows:makeClaimRows(key),generatedAt:Date.now()};}}
function renderClaimMonthOptions(){const allowed=new Set(claimWindowMonths());const months=state.selectedMonths.filter(m=>allowed.has(m)).sort();if(!months.length){$('claimMonthSelect').innerHTML='<option value="">No selected months</option>';state.activeMonth='';$('claimMonthPosition').textContent='';updateWorkflowHints();return}if(!state.activeMonth||!months.includes(state.activeMonth))state.activeMonth=months[0];$('claimMonthSelect').innerHTML=months.map(m=>`<option value="${m}">${monthLabel(m)}</option>`).join('');$('claimMonthSelect').value=state.activeMonth;const idx=months.indexOf(state.activeMonth);$('claimMonthPosition').textContent=`Month ${idx+1} of ${months.length}`;$('prevClaimMonth').disabled=idx<=0;$('nextClaimMonth').disabled=idx>=months.length-1;updateWorkflowHints();saveState();}
$('claimMonthSelect').addEventListener('change',()=>{state.activeMonth=$('claimMonthSelect').value;saveState();generateClaim(true);});
function claimableEvents(){return allEventItems().filter(e=>e.status==='Claim').sort((a,b)=>new Date(a.start)-new Date(b.start));}
function includesNightHours(start,end){const s=new Date(start),e=new Date(end);if(e<=s)return false;const cursor=new Date(s);cursor.setHours(0,0,0,0);while(cursor<e){const nightStart=new Date(cursor),nightEnd=new Date(cursor);nightEnd.setHours(6,0,0,0);if(Math.max(s.getTime(),nightStart.getTime())<Math.min(e.getTime(),nightEnd.getTime()))return true;cursor.setDate(cursor.getDate()+1);}return false;}
function generatedShiftLabel(e){
  if(e.source==='manual') return String(e.summary||'Unscheduled work').trim()||'Unscheduled work';
  const text=((e.summary||'')+' '+(e.description||'')).toLowerCase();
  if(/study/.test(text)) return 'Self-Development Time';
  const start=new Date(e.start),end=new Date(e.end||e.start),durationH=Math.max(0,(end-start)/3600000);
  if(includesNightHours(start,end)) return 'Night Shift';
  const sameDay=start.getFullYear()===end.getFullYear()&&start.getMonth()===end.getMonth()&&start.getDate()===end.getDate();
  const startMinutes=start.getHours()*60+start.getMinutes(),endMinutes=end.getHours()*60+end.getMinutes();
  if(durationH>=10&&startMinutes>=13*60&&endMinutes>=23*60&&sameDay) return 'Long evening Shift';
  if(durationH>=10&&sameDay&&endMinutes<24*60) return 'Long day';
  if(durationH>10) return 'Long shift';
  if(endMinutes<13*60&&sameDay) return 'Morning shift';
  if(endMinutes>22*60&&sameDay) return 'Evening shift';
  if(durationH<10&&startMinutes>=12*60&&sameDay) return 'Afternoon shift';
  if(durationH<10&&endMinutes<22*60&&sameDay) return 'Day shift';
  return 'Day shift';
}
function groupLinkedEvents(events){const groups=[];for(const e of events){const start=new Date(e.start),end=new Date(e.end||e.start);const last=groups[groups.length-1];if(last){const prevEnd=new Date(last[last.length-1].end||last[last.length-1].start);const gap=start-prevEnd;if(Math.abs(gap)<=60*60*1000){last.push(e);continue;}}groups.push([e]);}return groups;}
function makeClaimRows(key){
  const rows=[],commute=Number(state.settings.commuteMinutes)||0,miles=state.settings.claimableMiles===''?'':Number(state.settings.claimableMiles),passenger=state.settings.passengerMiles===''?'':Number(state.settings.passengerMiles),miscCost=Number(state.settings.commuteCost)||0,label=state.settings.commuteCostLabel||'Toll / travel',base=BASES[state.settings.baseSite]||BASES.DPOW,home=getPostcode(state.settings.homeAddress);
  for(const group of groupLinkedEvents(claimableEvents())){
    const first=group[0],last=group[group.length-1],firstStart=new Date(first.start),lastEnd=new Date(last.end||last.start),outDate=addMinutes(firstStart,-commute),homeArrive=addMinutes(lastEnd,commute);
    const firstLabel=generatedShiftLabel(first),lastLabel=generatedShiftLabel(last);
    const generated=[
      {id:first.id+'-out',date:outDate,start:outDate,end:firstStart,detail:`Work bound, ${firstLabel}`,from:home,to:base.postcode,miles,passengerMiles:passenger,miscLabel:state.settings.commuteType==='none'?'':label,miscAmount:state.settings.commuteType==='none'?'':miscCost,mealFrom:'',mealTo:'',mealAmount:'',direction:'out',eventId:first.id},
      {id:last.id+'-home',date:lastEnd,start:lastEnd,end:homeArrive,detail:`Home bound, ${lastLabel}`,from:base.postcode,to:home,miles,passengerMiles:passenger,miscLabel:state.settings.commuteType==='none'?'':label,miscAmount:state.settings.commuteType==='none'?'':miscCost,mealFrom:'',mealTo:'',mealAmount:'',direction:'home',eventId:last.id}
    ];
    rows.push(...generated.filter(r=>monthKey(r.date)===key));
  }
  return rows;
}
function renderClaimHeader(key){$('pName').textContent=state.settings.fullName;$('pMonth').textContent=monthLabel(key);$('pBase').textContent=state.settings.baseSite;$('pPersonal').textContent=formatPersonalNumber(state.settings.personalNumber);$('pDesignation').textContent=state.settings.designation;$('pVehicle').textContent=state.settings.vehicleReg;$('pEngine').textContent=state.settings.engineCc;$('pAddress').textContent=formatAddressLines(state.settings.homeAddress).join('\n');$('signatureDate').textContent=state.claims[key]?.signedDate||'';$('signaturePreview').innerHTML=state.signature?`<img class="sig-image" src="${state.signature}" alt="Claimant signature">`:'';}
function generateClaim(force=false){const key=state.activeMonth;if(!key)return;const previous=state.claims[key]||{};const rows=!force&&previous.rows?.length?previous.rows:makeClaimRows(key);state.claims[key]={...previous,rows,generatedAt:Date.now(),exportedAt:force?null:previous.exportedAt||null};renderClaimHeader(key);renderClaimRows(rows,false);updateWorkflowHints();saveState();}
function inputCell(i,key,value,type='text'){return `<input class="row-input" data-row="${i}" data-field="${key}" type="${type==='date'?'text':type}" value="${escapeHtml(value??'')}">`}
function renderClaimRows(rows,editing=false){const body=$('claimRows');body.innerHTML=rows.map((r,i)=>`<tr data-row="${i}"><td>${editing?inputCell(i,'date',displayDate(r.date)) : displayDate(r.date)}</td><td>R</td><td>${editing?inputCell(i,'start',parseTimeFromDate(r.start),'time'):parseTimeFromDate(r.start)}</td><td>${editing?inputCell(i,'detail',r.detail):escapeHtml(r.detail)}</td><td>${editing?inputCell(i,'end',parseTimeFromDate(r.end),'time'):parseTimeFromDate(r.end)}</td><td>${editing?inputCell(i,'from',r.from):escapeHtml(r.from)}</td><td>${editing?inputCell(i,'to',r.to):escapeHtml(r.to)}</td><td>${editing?inputCell(i,'miles',r.miles??'','number'):fmtNum(r.miles)}</td><td>${editing?inputCell(i,'passengerMiles',r.passengerMiles??'','number'):fmtNum(r.passengerMiles)}</td><td>${editing?inputCell(i,'miscLabel',r.miscLabel||''):escapeHtml(r.miscLabel||'')}</td><td>${editing?inputCell(i,'miscAmount',r.miscAmount??'','number'):money(r.miscAmount)}</td><td>${editing?inputCell(i,'mealFrom',r.mealFrom||'','time'):''}</td><td>${editing?inputCell(i,'mealTo',r.mealTo||'','time'):''}</td><td>${editing?inputCell(i,'mealAmount',r.mealAmount??'','number'):''}</td>${editing?`<td class="edit-cell"><button class="row-delete" data-row="${i}" title="Delete row">Delete</button></td>`:''}</tr>`).join('');
const totals=rows.reduce((a,r)=>(a.miles+=num(r.miles),a.pass+=num(r.passengerMiles),a.misc+=num(r.miscAmount),a.meals+=num(r.mealAmount),a),{miles:0,pass:0,misc:0,meals:0});$('totalMiles').textContent=fmtNum(totals.miles);$('totalPassengerMiles').textContent=fmtNum(totals.pass);$('totalMisc').textContent=money(totals.misc);$('totalMeals').textContent=money(totals.meals);$('claimTable').classList.toggle('claim-editing',editing);qsa('.row-add').forEach(x=>x.remove());qsa('#claimRows input').forEach(inp=>inp.addEventListener('input',onRowEdit));qsa('.row-delete').forEach(btn=>btn.addEventListener('click',()=>{const i=Number(btn.dataset.row);state.claims[state.activeMonth].rows.splice(i,1);renderClaimRows(state.claims[state.activeMonth].rows,true);saveState();}));if(editing){const add=document.createElement('button');add.className='row-add';add.textContent='+ Add row';add.addEventListener('click',()=>{state.claims[state.activeMonth].rows.push(blankRow());renderClaimRows(state.claims[state.activeMonth].rows,true);saveState();});body.closest('.table-scroll').appendChild(add);}}
function onRowEdit(e){const el=e.target,r=state.claims[state.activeMonth].rows[Number(el.dataset.row)],k=el.dataset.field;if(!r)return;if(k==='date'){const [d,m]=el.value.split('/');if(d&&m)r.date=new Date(Number(state.activeMonth.slice(0,4)),Number(m)-1,Number(d));}else if(k==='start'||k==='end'){const [h,mi]=el.value.split(':').map(Number),base=new Date(r.date);if(Number.isFinite(h)){base.setHours(h||0,mi||0,0,0);r[k]=base;}}else if(['miles','passengerMiles','miscAmount','mealAmount'].includes(k))r[k]=el.value===''?'':Number(el.value);else r[k]=el.value;saveState();}
function blankRow(){const now=new Date(),base=BASES[state.settings.baseSite]||BASES.DPOW,home=getPostcode(state.settings.homeAddress);return{id:'manual-row-'+Date.now(),date:now,start:now,end:now,detail:'',from:home,to:base.postcode,miles:'',passengerMiles:'',miscLabel:'',miscAmount:'',mealFrom:'',mealTo:'',mealAmount:''};}
function enableRowEditing(){if(!state.activeMonth||!state.claims[state.activeMonth]){showToast('Generate a claim first.');return}renderClaimRows(state.claims[state.activeMonth].rows,true);$('editBubble').hidden=true;showToast('Row editing enabled.');}
$('editRows').addEventListener('click',enableRowEditing);$('pageTwoPreview').addEventListener('click',e=>{if($('claimTable').classList.contains('claim-editing')||e.target.closest('input,button,select'))return;const b=$('editBubble');b.hidden=false;b.style.left=Math.min(window.innerWidth-150,e.clientX+10)+'px';b.style.top=Math.min(window.innerHeight-60,e.clientY+10)+'px';clearTimeout(window.__editBubbleTimer);window.__editBubbleTimer=setTimeout(()=>b.hidden=true,4500);});$('editBubbleBtn').addEventListener('click',enableRowEditing);
// Signature pad
let drawing=false,signatureDrawn=false,last={x:0,y:0};const canvas=$('signaturePad'),ctx=canvas.getContext('2d');ctx.lineWidth=2;ctx.lineCap='round';function pos(e){const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*(canvas.width/r.width),y:(p.clientY-r.top)*(canvas.height/r.height)}}function start(e){drawing=true;last=pos(e)}function move(e){if(!drawing)return;const p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();signatureDrawn=true;last=p;e.preventDefault()}function stop(){drawing=false}canvas.addEventListener('mousedown',start);canvas.addEventListener('mousemove',move);canvas.addEventListener('mouseup',stop);canvas.addEventListener('mouseleave',stop);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',stop);$('setupSignature').addEventListener('click',()=>{$('signatureDialog').showModal()});$('closeSig').addEventListener('click',()=>$('signatureDialog').close());$('clearSig').addEventListener('click',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signatureDrawn=false;});$('saveSig').addEventListener('click',()=>{if(!signatureDrawn){showToast('Please draw your signature first.');return}state.signature=canvas.toDataURL('image/png');state.signatureDate='';$('signatureDialog').close();if(state.activeMonth)renderClaimHeader(state.activeMonth);updateWorkflowHints();saveState();showToast('Sample signature saved locally.');});
// Template-based PDF export. The supplied Trust form is used as the background; only populated rows are drawn.
async function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Could not load PDF template'));im.src=src;});}
function wrapText(ctx,text,maxWidth){const words=String(text??'').split(/\s+/);const lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test;}if(line)lines.push(line);return lines;}
function drawTextFit(ctx,text,x,y,maxWidth,maxFont=14,minFont=7){let size=maxFont;ctx.font=size+'px Arial';while(size>minFont&&ctx.measureText(String(text??'')).width>maxWidth){size--;ctx.font=size+'px Arial';}ctx.fillText(String(text??''),x,y);return size;}
function drawPage1(ctx,img,key){ctx.drawImage(img,0,0,1404,992);ctx.fillStyle='#fff';ctx.fillRect(938,121,192,31);ctx.strokeStyle='#111';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(944,145);ctx.lineTo(1114,145);ctx.stroke();ctx.fillRect(1005,203,150,31);ctx.beginPath();ctx.moveTo(1010,226);ctx.lineTo(1140,226);ctx.stroke();ctx.fillStyle='#000';ctx.textBaseline='alphabetic';drawTextFit(ctx,state.settings.fullName,318,143,300,12,7);ctx.font='12px Arial';drawTextFit(ctx,monthLabel(key),944,140,166,12,7);drawTextFit(ctx,state.settings.baseSite,318,185,300,12,7);drawTextFit(ctx,state.settings.designation,318,228,300,12,7);drawTextFit(ctx,formatPersonalNumber(state.settings.personalNumber),1010,222,126,11,6);const addr=formatAddressLines(state.settings.homeAddress);addr.forEach((line,i)=>drawTextFit(ctx,line,318,265+i*20,300,11,6));drawTextFit(ctx,state.settings.vehicleReg,1010,266,130,11,6);drawTextFit(ctx,state.settings.engineCc,875,311,125,11,6);if(state.signature){const sig=new Image();sig.src=state.signature;ctx.drawImage(sig,318,620,250,36);}const signedDate=state.claims[key]?.signedDate||state.signatureDate||'';if(signedDate){drawTextFit(ctx,signedDate,872,667,190,10,7);}}
function drawPage2(ctx,img,rows){ctx.drawImage(img,0,0,1404,992);const bodyTop=114,rowH=24;const x=[28,93,152,212,512,571,665,760,819,919,1089,1166,1224,1283,1375];const bottom=bodyTop+rowH*rows.length,totalBottom=bottom+24;ctx.fillStyle='#fff';ctx.fillRect(28,bodyTop,1347,638);rows.forEach((r,i)=>{if(i%2===1){ctx.fillStyle='#eeeeee';ctx.fillRect(28,bodyTop+i*rowH,1347,rowH);}});ctx.strokeStyle='#111';ctx.lineWidth=1;ctx.beginPath();for(const xx of x){ctx.moveTo(xx,bodyTop);ctx.lineTo(xx,bottom)}for(let i=0;i<=rows.length;i++){const yy=bodyTop+i*rowH;ctx.moveTo(28,yy);ctx.lineTo(1375,yy)}ctx.stroke();ctx.fillStyle='#111';ctx.textAlign='center';ctx.textBaseline='middle';rows.forEach((r,i)=>{const y=bodyTop+i*rowH+rowH/2;ctx.font='9px Arial';ctx.fillText(displayDate(r.date),60,y);ctx.fillText('R',122,y);ctx.fillText(parseTimeFromDate(r.start),182,y);ctx.font='8px Arial';const lines=wrapText(ctx,r.detail,280);lines.slice(0,2).forEach((t,j)=>ctx.fillText(t,362,y+(j-.5)*9));ctx.font='9px Arial';ctx.fillText(parseTimeFromDate(r.end),541,y);ctx.font='8px Arial';ctx.fillText(r.from||'',618,y);ctx.fillText(r.to||'',712,y);ctx.font='9px Arial';ctx.fillText(fmtNum(r.miles),789,y);ctx.fillText(fmtNum(r.passengerMiles),869,y);ctx.font='7.5px Arial';const misc=wrapText(ctx,r.miscLabel||'',158);misc.slice(0,2).forEach((t,j)=>ctx.fillText(t,1004,y+(j-.5)*8));ctx.font='8.5px Arial';ctx.fillText(r.miscAmount?Number(r.miscAmount).toFixed(2):'',1127,y);});ctx.fillStyle='#fff';ctx.fillRect(512,bottom,854,24);ctx.strokeStyle='#111';ctx.strokeRect(512,bottom,248,24);ctx.strokeRect(760,bottom,59,24);ctx.strokeRect(919,bottom,170,24);ctx.strokeRect(1089,bottom,77,24);ctx.strokeRect(1224,bottom,59,24);ctx.strokeRect(1283,bottom,92,24);ctx.fillStyle='#111';ctx.font='bold 9px Arial';ctx.textAlign='center';ctx.fillText('TOTAL',636,bottom+12);ctx.fillText(fmtNum(rows.reduce((a,r)=>a+num(r.miles),0)),789,bottom+12);ctx.fillText('TOTAL',1004,bottom+12);ctx.fillText(money(rows.reduce((a,r)=>a+num(r.miscAmount),0)).replace('£',''),1127,bottom+12);ctx.fillText('TOTAL',1253,bottom+12);}
function canvasJpeg(canvas){return canvas.toDataURL('image/jpeg',0.9).split(',')[1];}
function base64Bytes(b64){const bin=atob(b64),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out;}
function makeImagePdf(jpegs,width,height){const imageObjs=[];let objNo=3;for(const b64 of jpegs){imageObjs.push({imgNo:objNo++,contentNo:objNo++,bytes:base64Bytes(b64)});}const pageNos=imageObjs.map(()=>objNo++),pagesNo=objNo++,catalogNo=objNo++;const chunks=[],offsets=[0];let pos=0;const enc=s=>new TextEncoder().encode(s);const add=bytes=>{chunks.push(bytes);pos+=bytes.length;};const addObj=(no,body,stream)=>{offsets[no]=pos;add(enc(no+' 0 obj\n'+body+(stream?'\nstream\n':'')));if(stream)add(stream);add(enc((stream?'\nendstream\n':'\n')+'endobj\n'));};add(enc('%PDF-1.3\n%âãÏÓ\n'));imageObjs.forEach((o,i)=>{addObj(o.imgNo,`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${o.bytes.length} >>`,o.bytes);const content=enc(`q\n841.89 0 0 595.28 0 0 cm\n/Im${i+1} Do\nQ\n`);addObj(o.contentNo,`<< /Length ${content.length} >>`,content);});pageNos.forEach((pno,i)=>addObj(pno,`<< /Type /Page /Parent ${pagesNo} 0 R /MediaBox [0 0 841.89 595.28] /Resources << /XObject << /Im${i+1} ${imageObjs[i].imgNo} 0 R >> >> /Contents ${imageObjs[i].contentNo} 0 R >>`));addObj(pagesNo,`<< /Type /Pages /Kids [${pageNos.map(n=>n+' 0 R').join(' ')}] /Count ${pageNos.length} >>`);addObj(catalogNo,`<< /Type /Catalog /Pages ${pagesNo} 0 R >>`);const xref=pos;add(enc('xref\n0 '+(catalogNo+1)+'\n0000000000 65535 f \n'));for(let i=1;i<=catalogNo;i++)add(enc(String(offsets[i]||0).padStart(10,'0')+' 00000 n \n'));add(enc(`trailer\n<< /Size ${catalogNo+1} /Root ${catalogNo} 0 R >>\nstartxref\n${xref}\n%%EOF`));const total=chunks.reduce((n,c)=>n+c.length,0),out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.length;}return new Blob([out],{type:'application/pdf'});}
async function exportPdfForMonth(key){if(!state.signature)throw new Error('Sample signature is missing.');if(!state.claims[key])state.claims[key]={rows:makeClaimRows(key),generatedAt:Date.now()};state.claims[key].signedDate=new Date().toLocaleDateString('en-GB');const rows=state.claims[key].rows.filter(r=>r.date);const [img1,img2]=await Promise.all([loadImage('template/page-1.jpg'),loadImage('template/page-2.jpg')]);const c1=document.createElement('canvas');c1.width=1404;c1.height=992;drawPage1(c1.getContext('2d'),img1,key);const jpegs=[canvasJpeg(c1)],pageSize=24;for(let i=0;i<rows.length||i===0;i+=pageSize){const chunk=rows.slice(i,i+pageSize),c=document.createElement('canvas');c.width=1404;c.height=992;drawPage2(c.getContext('2d'),img2,chunk);jpegs.push(canvasJpeg(c));if(i+pageSize>=rows.length)break;}const blob=makeImagePdf(jpegs,1404,992),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Travel Claim - ${key}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500);state.claims[key].exportedAt=new Date().toISOString();addExpenseLogForMonth(key);saveState();return jpegs.length;}
function addExpenseLogForMonth(key){if(state.expenseLog.some(x=>x.month===key))return;const rows=state.claims[key]?.rows||[],miles=rows.reduce((a,r)=>a+num(r.miles),0),misc=rows.reduce((a,r)=>a+num(r.miscAmount),0),totalMiles=miles*(Number(state.settings.mileageRate)||0.30),dates=rows.map(r=>new Date(r.date)).sort((a,b)=>a-b);state.expenseLog.push({id:'log-'+Date.now()+'-'+key,submitted:new Date().toISOString(),range:dates.length?`${dates[0].toLocaleDateString('en-GB')} - ${dates[dates.length-1].toLocaleDateString('en-GB')}`:monthLabel(key),miles,totalMiles,misc,total:totalMiles+misc,month:key});}
$('signAndSave').addEventListener('click',async()=>{if(!validateSetup())return;const key=state.activeMonth;if(!key){showToast('Select a claim month first.');return}try{$('signAndSave').disabled=true;await exportPdfForMonth(key);renderClaimHeader(key);renderExpenseLog();updateWorkflowHints();showToast(`Signed PDF saved for ${monthLabel(key)}.`);}catch(e){console.error(e);showToast(e.message||'PDF export failed.');}finally{$('signAndSave').disabled=false;}});
$('humberBridge').addEventListener('click',()=>{if(state.settings.commuteType==='toll')window.open('https://toll.humberbridge.co.uk/','_blank','noopener');});
function selectedMonthsPhrase(){return state.selectedMonths.slice().sort().map(monthLabel).join(', ');}
$('emailPayroll').addEventListener('click',()=>{const parts=String(state.settings.fullName||'').trim().split(/\s+/),surname=parts.at(-1)||'',first=parts[0]||'',months=selectedMonthsPhrase()||monthLabel(state.activeMonth),subject=`${surname} - Travel expenses for ${months}`,body=`Payroll number: ${state.settings.personalNumber}\n\nDear Payroll,\n\nPlease find completed travel expenses form/s ± proof of toll crossings attached. These cover ${months}.\n\nRegards\n\n${first} ${surname}\n${state.settings.designation}`;location.href=`mailto:nlg-tr.payrollenquiries@nhs.net?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;});
function renderExpenseLog(){const body=$('logBody');body.innerHTML=state.expenseLog.map(x=>`<tr><td>${new Date(x.submitted).toLocaleDateString('en-GB')}</td><td>${escapeHtml(x.range)}</td><td>${money(x.totalMiles)}</td><td>${money(x.misc)}</td><td><b>${money(x.total)}</b></td><td><button class="log-delete" data-id="${escapeAttr(x.id)}">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" class="hint">No submitted claims yet.</td></tr>';const total=state.expenseLog.reduce((a,x)=>a+num(x.total),0);$('logTotal').textContent=money(total);qsa('.log-delete').forEach(b=>b.addEventListener('click',()=>{state.expenseLog=state.expenseLog.filter(x=>x.id!==b.dataset.id);saveState();renderExpenseLog();}));}
$('backupBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='travel-claims-manager-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
$('restoreInput').addEventListener('change',async()=>{const f=$('restoreInput').files[0];if(!f)return;try{state=mergeState(JSON.parse(await f.text()));bindSettings(true);$('icsUrl').value=state.icsUrl;renderAll();if(state.activeMonth)generateClaim(false);saveState();showToast('Backup restored.');}catch(e){showToast('Backup file could not be loaded.');}});
function renderCalendarSource(){$('calendarSourceLabel').textContent='Calendar refreshes automatically through the built-in secure Cloudflare Worker when Shifts opens.';}
function renderAll(){renderMonths();renderShifts();renderClaimMonthOptions();renderExpenseLog();renderCalendarSource();if(state.activeMonth)renderClaimHeader(state.activeMonth);updateWorkflowHints();}
// PWA install UI
const installBtn=$('installApp');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;installBtn.hidden=false;});installBtn.addEventListener('click',async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installBtn.hidden=true;}else if(/iphone|ipad|ipod/i.test(navigator.userAgent)){alert('In Safari: Share → Add to Home Screen → turn on Open as Web App → Add.');}});
window.addEventListener('appinstalled',()=>{installBtn.hidden=true;showToast('Travel Claims Manager installed.');});
bindSettings();renderAll();switchTab(location.hash.slice(1)||'setup');if(state.activeMonth&&state.claims[state.activeMonth])generateClaim(false);recoverFromCache();
if('serviceWorker' in navigator&&(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'))navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
