(function(){
'use strict';
const STORAGE_KEY='travelClaimsManagerStateV2';
const COOKIE_KEY='travelClaimsManagerVersion';
const CACHE_NAME='travel-claims-manager-state-v2';
const BASES={DPOW:{name:'DPOW',postcode:'DN33 2BA'},SGH:{name:'SGH',postcode:'DN15 7BH'}};
const DEFAULT_STATE={settings:{fullName:'',baseSite:'DPOW',designation:'',personalNumber:'',homeAddress:'',vehicleReg:'',engineCc:'',claimableMiles:'',passengerMiles:'',commuteMinutes:30,mileageRate:0.30,commuteType:'none',commuteCost:'',commuteCostLabel:'Humber toll'},icsUrl:'',proxy:'auto',events:[],selectedMonths:[],manualEvents:[],claims:{},expenseLog:[],activeMonth:'',signature:null,signatureDate:''};
let state=loadState();let saveTimer;let deferredInstallPrompt=null;
const $=id=>document.getElementById(id),qsa=s=>Array.from(document.querySelectorAll(s));
const clone=o=>JSON.parse(JSON.stringify(o));
function mergeState(saved){const base=clone(DEFAULT_STATE);if(!saved||typeof saved!=='object')return base;return {...base,...saved,settings:{...base.settings,...(saved.settings||{})},claims:saved.claims||{},events:Array.isArray(saved.events)?saved.events:[],manualEvents:Array.isArray(saved.manualEvents)?saved.manualEvents:[],selectedMonths:Array.isArray(saved.selectedMonths)?saved.selectedMonths:[],expenseLog:Array.isArray(saved.expenseLog)?saved.expenseLog:[]};}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)return mergeState(JSON.parse(raw));}catch(e){}try{const raw=localStorage.getItem('travelClaimsManagerStateV1');if(raw)return mergeState(JSON.parse(raw));}catch(e){}return clone(DEFAULT_STATE);}
async function recoverFromCache(){if(localStorage.getItem(STORAGE_KEY)||!window.caches)return;try{const c=await caches.open(CACHE_NAME);const r=await c.match(new Request(location.origin+'/__travel_claims_state__'));if(r){state=mergeState(await r.json());bindSettings(true);renderAll();showToast('Recovered your latest local draft.');}}catch(e){}}
function saveState(){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{const serial=JSON.stringify(state);localStorage.setItem(STORAGE_KEY,serial);document.cookie=COOKIE_KEY+'=2; max-age=31536000; samesite=lax; path=/';if(window.caches&&location.protocol!=='file:'){const c=await caches.open(CACHE_NAME);await c.put(new Request(location.origin+'/__travel_claims_state__'),new Response(serial,{headers:{'Content-Type':'application/json'}}));}$('saveStatus').textContent='Saved locally · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}catch(e){$('saveStatus').textContent='Local save warning';}},150);}
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2600);}
function switchTab(name){qsa('.tab').forEach(b=>{const active=b.dataset.tab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));});qsa('.panel').forEach(p=>{const active=p.id===name;p.classList.toggle('active',active);p.hidden=!active;});if(name==='claim')renderClaimMonthOptions();if(name==='log')renderExpenseLog();}
function navigate(name){switchTab(name);try{history.replaceState(null,'','#'+name)}catch(e){location.hash=name}window.scrollTo(0,0);}
qsa('.tab').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.tab)));
$('setupContinue').addEventListener('click',e=>{e.preventDefault();navigate('shifts');});
window.addEventListener('hashchange',()=>{const n=location.hash.slice(1);if(['setup','shifts','claim','log'].includes(n))switchTab(n);});
function monthKey(date){const d=new Date(date);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');}
function monthLabel(key){const [y,m]=key.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString(undefined,{month:'long',year:'numeric'});}
function fmtDateTime(dt){const d=new Date(dt);return d.toLocaleDateString(undefined,{day:'2-digit',month:'2-digit'})+' '+d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}
function displayDate(d){const x=new Date(d);return String(x.getDate()).padStart(2,'0')+'/'+String(x.getMonth()+1).padStart(2,'0');}
function parseTimeFromDate(d){return new Date(d).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',hour12:false});}
function addMinutes(d,n){return new Date(new Date(d).getTime()+n*60000);}
function num(v){return Number(v)||0;}function fmtNum(v){const n=Number(v);return n?String(Number(n.toFixed(1))):'';}function money(v){const n=Number(v)||0;return n?'£'+n.toFixed(2):'';}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;');}
function getPostcode(addr){const m=String(addr||'').match(/[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}/i);return m?m[0].toUpperCase():String(addr||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean).slice(-1)[0]||'';}
function bindSettings(rebind=false){const ids=['fullName','baseSite','designation','personalNumber','homeAddress','vehicleReg','engineCc','claimableMiles','passengerMiles','commuteMinutes','mileageRate','commuteType','commuteCost','commuteCostLabel'];ids.forEach(id=>{const el=$(id);el.value=state.settings[id]??'';if(!rebind&&!el.dataset.bound){const save=()=>{state.settings[id]=el.value;saveState();};el.addEventListener('input',save);el.addEventListener('change',save);el.dataset.bound='1';}});}
function normalizeUrl(url){let u=String(url||'').trim();if(u.startsWith('webcal://'))u='https://'+u.slice(9);return u;}
function unfoldICS(text){const lines=text.replace(/\r\n/g,'\n').replace(/\r/g,'\n').split('\n');const out=[];for(const line of lines){if(/^[ \t]/.test(line)&&out.length)out[out.length-1]+=line.slice(1);else out.push(line);}return out;}
function unescapeText(s){return String(s??'').replace(/\\n/g,'\n').replace(/\\,/g,',').replace(/\\;/g,';').replace(/\\\\/g,'\\');}
function icsDate(v){if(!v)return null;let s=String(v).replace(/^.*?:/,'');if(/^\d{8}$/.test(s))return new Date(Number(s.slice(0,4)),Number(s.slice(4,6))-1,Number(s.slice(6,8)),9,0,0);const z=s.endsWith('Z');if(z)s=s.slice(0,-1);const y=+s.slice(0,4),mo=+s.slice(4,6)-1,d=+s.slice(6,8),h=+(s.slice(9,11)||0),mi=+(s.slice(11,13)||0),sec=+(s.slice(13,15)||0);return z?new Date(Date.UTC(y,mo,d,h,mi,sec)):new Date(y,mo,d,h,mi,sec);}
function parseCalendarFallback(text){const lines=unfoldICS(text),events=[];let cur=null;for(const line of lines){if(line==='BEGIN:VEVENT'){cur={};continue}if(line==='END:VEVENT'){if(cur?.dtstart)events.push(cur);cur=null;continue}if(!cur)continue;const m=line.match(/^([A-Z0-9-]+)(?:;[^:]*)?:(.*)$/);if(m)cur[m[1].toLowerCase()]=m[2];}
return expandSimpleRecurrence(events.map((e,i)=>({uid:e.uid||'fallback-'+i,summary:unescapeText(e.summary||'Shift'),description:unescapeText(e.description||''),start:icsDate(e.dtstart),end:icsDate(e.dtend||e.dtstart),allDay:(e.dtstart||'').length===8,rrule:e.rrule||'',exdate:e.exdate||''})).filter(e=>e.start));}
function expandSimpleRecurrence(events){const out=[];const limit=new Date(Date.now()+1000*60*60*24*366*3);for(const e of events){const duration=(e.end?.getTime()||e.start.getTime()+3600000)-e.start.getTime();const rule=e.rrule||'';if(!rule){out.push(e);continue}const parts={};rule.split(';').forEach(x=>{const [k,v]=x.split('=');parts[k]=v});const freq=parts.FREQ;let interval=Number(parts.INTERVAL||1),count=Number(parts.COUNT||0),until=parts.UNTIL?icsDate(parts.UNTIL):null;let cur=new Date(e.start),n=0;while(cur<=limit&&(until?cur<=until:true)&&(count? n<count:true)){out.push({...e,uid:e.uid+'-'+n,start:new Date(cur),end:new Date(cur.getTime()+duration)});n++;if(freq==='DAILY')cur.setDate(cur.getDate()+interval);else if(freq==='WEEKLY')cur.setDate(cur.getDate()+7*interval);else if(freq==='MONTHLY')cur.setMonth(cur.getMonth()+interval);else break} }return out;}
function inferStatus(e){const s=(e.summary+' '+(e.description||'')).toLowerCase();if(/annual|holiday|a\/l|leave/.test(s))return 'Annual leave';if(/study/.test(s))return 'Study leave';if(/sick|sickness/.test(s))return 'Sick';if(/strike/.test(s))return 'Strike';return 'Claim';}
async function fetchWithTimeout(url,ms=12000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text();}finally{clearTimeout(timer);}}
async function fetchText(url,mode){const u=normalizeUrl(url);const targets=[];if(mode==='auto'||mode==='direct')targets.push(u);if(mode!=='direct'){targets.push('https://corsproxy.io/?url='+encodeURIComponent(u));targets.push('https://api.allorigins.win/raw?url='+encodeURIComponent(u));targets.push('https://cors.isomorphic-git.org/'+u);}let last=null;for(const target of targets){try{const text=await fetchWithTimeout(target);if(/BEGIN:(?:VCALENDAR|VEVENT)/i.test(text))return text;last=new Error('Response was not an ICS calendar.');}catch(e){last=e;}}throw last||new Error('Unable to fetch calendar.');}
function applyCalendarText(text,source){const parsed=parseCalendarFallback(text);if(!parsed.length)throw new Error('No calendar events were found.');state.events=parsed.map((e,i)=>({...e,id:e.uid+'-'+i,status:inferStatus(e),source}));const months=[...new Set(state.events.map(e=>monthKey(e.start)))].sort();state.selectedMonths=state.selectedMonths.filter(m=>months.includes(m));if(!state.selectedMonths.length)state.selectedMonths=months.slice(0,2);renderAll();saveState();}
async function loadIcs(){state.icsUrl=$('icsUrl').value.trim();state.proxy=$('proxySelect').value;saveState();if(!state.icsUrl){showToast('Paste an ICS URL first.');return}if(location.protocol==='file:'){showToast('URL fetching needs HTTPS or localhost. Use direct .ics import here, or host the PWA.');return}$('fetchIcs').disabled=true;$('refreshIcs').disabled=true;$('icsState').textContent='Fetching calendar…';try{const text=await fetchText(state.icsUrl,state.proxy);applyCalendarText(text,'ics');$('icsState').textContent=state.events.length+' events loaded';showToast('Calendar refreshed.');}catch(e){$('icsState').textContent='Calendar load failed';showToast((e.name==='AbortError'?'Proxy timed out. ': '')+(e.message||'Could not fetch calendar.'));}finally{$('fetchIcs').disabled=false;$('refreshIcs').disabled=false;}}
async function loadIcsFile(file){if(!file)return;try{const text=await file.text();if(!/BEGIN:(?:VCALENDAR|VEVENT)/i.test(text))throw new Error('The selected file does not look like an ICS calendar.');applyCalendarText(text,'file');$('icsState').textContent=state.events.length+' events loaded from file';showToast('ICS file imported locally.');}catch(e){$('icsState').textContent='ICS file load failed';showToast(e.message||'Could not read the ICS file.');}}
$('fetchIcs').addEventListener('click',loadIcs);$('refreshIcs').addEventListener('click',loadIcs);$('icsFile').addEventListener('change',e=>loadIcsFile(e.target.files[0]));$('icsUrl').value=state.icsUrl;$('proxySelect').value=state.proxy;
function allEventItems(){return [...state.events,...state.manualEvents];}
function renderMonths(){const months=[...new Set(allEventItems().map(e=>monthKey(e.start)))].sort();if(!months.length){$('monthPicker').className='month-picker empty';$('monthPicker').textContent='Fetch or import a calendar first.';return}$('monthPicker').className='month-picker';$('monthPicker').innerHTML=months.map(m=>`<label class="month-chip"><input type="checkbox" data-month="${m}" ${state.selectedMonths.includes(m)?'checked':''}>${monthLabel(m)}</label>`).join('');qsa('#monthPicker input').forEach(i=>i.addEventListener('change',()=>{state.selectedMonths=qsa('#monthPicker input:checked').map(x=>x.dataset.month);renderClaimMonthOptions();saveState();}));}
function renderShifts(){const items=allEventItems().sort((a,b)=>new Date(a.start)-new Date(b.start));if(!items.length){$('shiftList').className='shift-list empty';$('shiftList').textContent='No shifts loaded.';return}$('shiftList').className='shift-list';$('shiftList').innerHTML=items.map(e=>{const date=fmtDateTime(e.start),end=e.end?fmtDateTime(e.end):'';return `<div class="shift ${e.source==='manual'?'manual':''}" data-id="${escapeAttr(e.id)}"><div class="date">${date.split(' ')[0]}</div><div><div class="summary">${escapeHtml(e.summary||'Unscheduled travel')}</div><div class="times">${date.split(' ').slice(1).join(' ')}${end?' → '+end:''}</div></div><select class="shift-status"><option>Claim</option><option>Annual leave</option><option>Study leave</option><option>Sick</option><option>Strike</option><option>Do not claim</option></select><button class="delete" title="Delete shift" aria-label="Delete shift">×</button></div>`}).join('');qsa('.shift').forEach(row=>{const id=row.dataset.id,item=allEventItems().find(x=>x.id===id),sel=row.querySelector('select');sel.value=item.status;sel.addEventListener('change',()=>{item.status=sel.value;saveState();});row.querySelector('.delete').addEventListener('click',()=>{state.events=state.events.filter(x=>x.id!==id);state.manualEvents=state.manualEvents.filter(x=>x.id!==id);renderAll();saveState();});});}
$('selectAllMonths').addEventListener('click',()=>{state.selectedMonths=[...new Set(allEventItems().map(e=>monthKey(e.start)))].sort();renderAll();saveState();});$('clearMonths').addEventListener('click',()=>{state.selectedMonths=[];renderClaimMonthOptions();renderMonths();saveState();});
$('addManualShift').addEventListener('click',()=>{$('manualDate').value=new Date().toISOString().slice(0,10);$('manualStart').value='09:00';$('manualEnd').value='17:00';$('manualReason').value='';$('manualShiftDialog').showModal();});
$('manualShiftForm').addEventListener('submit',e=>{e.preventDefault();const date=$('manualDate').value,start=$('manualStart').value,end=$('manualEnd').value;if(!date||!start||!end)return;const s=new Date(date+'T'+start),en0=new Date(date+'T'+end),en=en0<=s?new Date(en0.getTime()+86400000):en0,id='manual-'+Date.now();state.manualEvents.push({id,uid:id,summary:$('manualReason').value.trim()||'Unscheduled work',description:'Manual travel',start:s.toISOString(),end:en.toISOString(),status:'Claim',source:'manual'});state.selectedMonths=[...new Set([...state.selectedMonths,monthKey(s)])];$('manualShiftDialog').close();renderAll();saveState();showToast('Unscheduled day added.');});
function renderClaimMonthOptions(){const months=state.selectedMonths.filter(m=>allEventItems().some(e=>monthKey(e.start)===m)).sort();if(!months.length){$('claimMonthSelect').innerHTML='<option value="">No selected months</option>';state.activeMonth='';return}if(!state.activeMonth||!months.includes(state.activeMonth))state.activeMonth=months[0];$('claimMonthSelect').innerHTML=months.map(m=>`<option value="${m}">${monthLabel(m)}</option>`).join('');$('claimMonthSelect').value=state.activeMonth;saveState();}
$('claimMonthSelect').addEventListener('change',()=>{state.activeMonth=$('claimMonthSelect').value;saveState();generateClaim(true);});$('generateClaim').addEventListener('click',()=>generateClaim(true));
function claimableEventsForMonth(key){return allEventItems().filter(e=>monthKey(e.start)===key&&e.status==='Claim').sort((a,b)=>new Date(a.start)-new Date(b.start));}
function makeClaimRows(key){const rows=[],commute=Number(state.settings.commuteMinutes)||0,miles=state.settings.claimableMiles===''?'':Number(state.settings.claimableMiles),passenger=state.settings.passengerMiles===''?'':Number(state.settings.passengerMiles),miscCost=Number(state.settings.commuteCost)||0,label=state.settings.commuteCostLabel||'Toll / travel',base=BASES[state.settings.baseSite]||BASES.DPOW,home=getPostcode(state.settings.homeAddress);for(const e of claimableEventsForMonth(key)){const start=new Date(e.start),end=new Date(e.end||e.start),outDate=addMinutes(start,-commute),homeArrive=addMinutes(end,commute);rows.push({id:e.id+'-out',date:outDate,start:outDate,end:start,detail:e.summary?`Work bound, ${e.summary}`:'Work bound',from:home,to:base.postcode,miles,passengerMiles:passenger,miscLabel:state.settings.commuteType==='none'?'':label,miscAmount:state.settings.commuteType==='none'?'':miscCost,mealFrom:'',mealTo:'',mealAmount:'',direction:'out',eventId:e.id});rows.push({id:e.id+'-home',date:end,start:end,end:homeArrive,detail:e.summary?`Home bound, ${e.summary}`:'Home bound',from:base.postcode,to:home,miles,passengerMiles:passenger,miscLabel:state.settings.commuteType==='none'?'':label,miscAmount:state.settings.commuteType==='none'?'':miscCost,mealFrom:'',mealTo:'',mealAmount:'',direction:'home',eventId:e.id});}return rows;}
function renderClaimHeader(key){$('pName').textContent=state.settings.fullName;$('pMonth').textContent=monthLabel(key);$('pBase').textContent=state.settings.baseSite;$('pPersonal').textContent=state.settings.personalNumber;$('pDesignation').textContent=state.settings.designation;$('pVehicle').textContent=state.settings.vehicleReg;$('pEngine').textContent=state.settings.engineCc;$('pAddress').textContent=state.settings.homeAddress;$('signatureDate').textContent=state.signatureDate||'';$('signaturePreview').innerHTML=state.signature?`<img class="sig-image" src="${state.signature}" alt="Claimant signature">`:'';}
function generateClaim(force=false){const key=state.activeMonth;if(!key)return;const rows=!force&&state.claims[key]?.rows?.length?state.claims[key].rows:makeClaimRows(key);state.claims[key]={rows,generatedAt:Date.now()};renderClaimHeader(key);renderClaimRows(rows,false);saveState();}
function inputCell(i,key,value,type='text'){return `<input class="row-input" data-row="${i}" data-field="${key}" type="${type==='date'?'text':type}" value="${escapeHtml(value??'')}">`}
function renderClaimRows(rows,editing=false){const body=$('claimRows');body.innerHTML=rows.map((r,i)=>`<tr data-row="${i}"><td>${editing?inputCell(i,'date',displayDate(r.date)) : displayDate(r.date)}</td><td>R</td><td>${editing?inputCell(i,'start',parseTimeFromDate(r.start),'time'):parseTimeFromDate(r.start)}</td><td>${editing?inputCell(i,'detail',r.detail):escapeHtml(r.detail)}</td><td>${editing?inputCell(i,'end',parseTimeFromDate(r.end),'time'):parseTimeFromDate(r.end)}</td><td>${editing?inputCell(i,'from',r.from):escapeHtml(r.from)}</td><td>${editing?inputCell(i,'to',r.to):escapeHtml(r.to)}</td><td>${editing?inputCell(i,'miles',r.miles??'','number'):fmtNum(r.miles)}</td><td>${editing?inputCell(i,'passengerMiles',r.passengerMiles??'','number'):fmtNum(r.passengerMiles)}</td><td>${editing?inputCell(i,'miscLabel',r.miscLabel||''):escapeHtml(r.miscLabel||'')}</td><td>${editing?inputCell(i,'miscAmount',r.miscAmount??'','number'):money(r.miscAmount)}</td><td>${editing?inputCell(i,'mealFrom',r.mealFrom||'','time'):''}</td><td>${editing?inputCell(i,'mealTo',r.mealTo||'','time'):''}</td><td>${editing?inputCell(i,'mealAmount',r.mealAmount??'','number'):''}</td>${editing?`<td class="edit-cell"><button class="row-delete" data-row="${i}" title="Delete row">Delete</button></td>`:''}</tr>`).join('');
const totals=rows.reduce((a,r)=>(a.miles+=num(r.miles),a.pass+=num(r.passengerMiles),a.misc+=num(r.miscAmount),a.meals+=num(r.mealAmount),a),{miles:0,pass:0,misc:0,meals:0});$('totalMiles').textContent=fmtNum(totals.miles);$('totalPassengerMiles').textContent=fmtNum(totals.pass);$('totalMisc').textContent=money(totals.misc);$('totalMeals').textContent=money(totals.meals);$('claimTable').classList.toggle('claim-editing',editing);qsa('.row-add').forEach(x=>x.remove());qsa('#claimRows input').forEach(inp=>inp.addEventListener('input',onRowEdit));qsa('.row-delete').forEach(btn=>btn.addEventListener('click',()=>{const i=Number(btn.dataset.row);state.claims[state.activeMonth].rows.splice(i,1);renderClaimRows(state.claims[state.activeMonth].rows,true);saveState();}));if(editing){const add=document.createElement('button');add.className='row-add';add.textContent='+ Add row';add.addEventListener('click',()=>{state.claims[state.activeMonth].rows.push(blankRow());renderClaimRows(state.claims[state.activeMonth].rows,true);saveState();});body.closest('.table-scroll').appendChild(add);}}
function onRowEdit(e){const el=e.target,r=state.claims[state.activeMonth].rows[Number(el.dataset.row)],k=el.dataset.field;if(!r)return;if(k==='date'){const [d,m]=el.value.split('/');if(d&&m)r.date=new Date(Number(state.activeMonth.slice(0,4)),Number(m)-1,Number(d));}else if(k==='start'||k==='end'){const [h,mi]=el.value.split(':').map(Number),base=new Date(r.date);if(Number.isFinite(h)){base.setHours(h||0,mi||0,0,0);r[k]=base;}}else if(['miles','passengerMiles','miscAmount','mealAmount'].includes(k))r[k]=el.value===''?'':Number(el.value);else r[k]=el.value;saveState();}
function blankRow(){const now=new Date(),base=BASES[state.settings.baseSite]||BASES.DPOW,home=getPostcode(state.settings.homeAddress);return{id:'manual-row-'+Date.now(),date:now,start:now,end:now,detail:'',from:home,to:base.postcode,miles:'',passengerMiles:'',miscLabel:'',miscAmount:'',mealFrom:'',mealTo:'',mealAmount:''};}
$('editRows').addEventListener('click',()=>{if(!state.activeMonth||!state.claims[state.activeMonth]){showToast('Generate a claim first.');return}renderClaimRows(state.claims[state.activeMonth].rows,true);showToast('Row editing enabled.');});
// Signature pad
let drawing=false,last={x:0,y:0};const canvas=$('signaturePad'),ctx=canvas.getContext('2d');ctx.lineWidth=2;ctx.lineCap='round';function pos(e){const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*(canvas.width/r.width),y:(p.clientY-r.top)*(canvas.height/r.height)}}function start(e){drawing=true;last=pos(e)}function move(e){if(!drawing)return;const p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;e.preventDefault()}function stop(){drawing=false}canvas.addEventListener('mousedown',start);canvas.addEventListener('mousemove',move);canvas.addEventListener('mouseup',stop);canvas.addEventListener('mouseleave',stop);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',stop);$('signForm').addEventListener('click',()=>{$('signatureDialog').showModal()});$('closeSig').addEventListener('click',()=>$('signatureDialog').close());$('clearSig').addEventListener('click',()=>ctx.clearRect(0,0,canvas.width,canvas.height));$('saveSig').addEventListener('click',()=>{state.signature=canvas.toDataURL('image/png');state.signatureDate=new Date().toLocaleDateString('en-GB');$('signatureDialog').close();renderClaimHeader(state.activeMonth);saveState();showToast('Signature saved locally.');});
// Template-based PDF export. The supplied Trust form is used as the background; only populated rows are drawn.
async function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Could not load PDF template'));im.src=src;});}
function wrapText(ctx,text,maxWidth){const words=String(text??'').split(/\s+/);const lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test;}if(line)lines.push(line);return lines;}
function drawTextFit(ctx,text,x,y,maxWidth,maxFont=14,minFont=7){let size=maxFont;ctx.font=size+'px Arial';while(size>minFont&&ctx.measureText(String(text??'')).width>maxWidth){size--;ctx.font=size+'px Arial';}ctx.fillText(String(text??''),x,y);return size;}
function drawPage1(ctx,img,key){ctx.drawImage(img,0,0,1404,992);ctx.fillStyle='#000';ctx.textBaseline='alphabetic';ctx.font='14px Arial';drawTextFit(ctx,state.settings.fullName,318,143,300,14,8);ctx.font='bold 14px Arial';drawTextFit(ctx,monthLabel(key),944,143,250,14,8);ctx.font='14px Arial';drawTextFit(ctx,state.settings.baseSite,318,185,300);drawTextFit(ctx,state.settings.designation,318,228,300);drawTextFit(ctx,state.settings.personalNumber,1010,228,220);const addr=String(state.settings.homeAddress||'').split(/\r?\n/).filter(Boolean).slice(0,4);addr.forEach((line,i)=>drawTextFit(ctx,line,318,265+i*24,300,13,7));drawTextFit(ctx,state.settings.vehicleReg,1010,266,220);drawTextFit(ctx,state.settings.engineCc,875,311,150);if(state.signature){const sig=new Image();sig.src=state.signature;ctx.drawImage(sig,318,651,250,45);}if(state.signatureDate){ctx.font='12px Arial';drawTextFit(ctx,state.signatureDate,872,667,200,12,8);}}
function drawPage2(ctx,img,rows){ctx.drawImage(img,0,0,1404,992);const bodyTop=118,bodyBottom=680,fullHeight=bodyBottom-bodyTop,rowH=Math.max(26,Math.min(42,fullHeight/Math.max(rows.length,1)));ctx.fillStyle='#fff';ctx.fillRect(23,bodyTop,1361,bodyBottom-bodyTop+1);ctx.strokeStyle='#111';ctx.lineWidth=1;const x=[23,79,135,185,516,584,673,756,816,907,1099,1174,1249,1301,1384];ctx.beginPath();for(const xx of x){ctx.moveTo(xx,bodyTop);ctx.lineTo(xx,bodyTop+rowH*rows.length)}for(let i=0;i<=rows.length;i++){const yy=bodyTop+i*rowH;ctx.moveTo(23,yy);ctx.lineTo(1384,yy)}ctx.stroke();ctx.fillStyle='#111';ctx.textAlign='center';ctx.textBaseline='middle';rows.forEach((r,i)=>{const y=bodyTop+i*rowH+rowH/2;ctx.font='10px Arial';ctx.fillText(displayDate(r.date),51,y);ctx.fillText('R',107,y);ctx.fillText(parseTimeFromDate(r.start),160,y);ctx.font='9px Arial';const lines=wrapText(ctx,r.detail,320);lines.slice(0,2).forEach((t,j)=>ctx.fillText(t,350,y+(j-.5)*11));ctx.font='10px Arial';ctx.fillText(parseTimeFromDate(r.end),550,y);ctx.font='9px Arial';ctx.fillText(r.from||'',628,y);ctx.fillText(r.to||'',714,y);ctx.font='10px Arial';ctx.fillText(fmtNum(r.miles),786,y);ctx.fillText(fmtNum(r.passengerMiles),861,y);ctx.font='8px Arial';const misc=wrapText(ctx,r.miscLabel||'',180);misc.slice(0,2).forEach((t,j)=>ctx.fillText(t,1003,y+(j-.5)*10));ctx.font='9px Arial';ctx.fillText(r.miscAmount?Number(r.miscAmount).toFixed(2):'',1136,y);});const totalY=bodyTop+rowH*rows.length;ctx.font='bold 10px Arial';ctx.textAlign='right';ctx.fillText('TOTAL',756,totalY+13);ctx.fillText(fmtNum(rows.reduce((a,r)=>a+num(r.miles),0)),805,totalY+13);ctx.fillText(fmtNum(rows.reduce((a,r)=>a+num(r.passengerMiles),0)),896,totalY+13);ctx.fillText('TOTAL',1090,totalY+13);ctx.fillText(money(rows.reduce((a,r)=>a+num(r.miscAmount),0)).replace('£',''),1162,totalY+13);}
function canvasJpeg(canvas){return canvas.toDataURL('image/jpeg',0.9).split(',')[1];}
function base64Bytes(b64){const bin=atob(b64),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out;}
function makeImagePdf(jpegs,width,height){const imageObjs=[];let objNo=3;for(const b64 of jpegs){imageObjs.push({imgNo:objNo++,contentNo:objNo++,bytes:base64Bytes(b64)});}const pageNos=imageObjs.map(()=>objNo++),pagesNo=objNo++,catalogNo=objNo++;const chunks=[],offsets=[0];let pos=0;const enc=s=>new TextEncoder().encode(s);const add=bytes=>{chunks.push(bytes);pos+=bytes.length;};const addObj=(no,body,stream)=>{offsets[no]=pos;add(enc(no+' 0 obj\n'+body+(stream?'\nstream\n':'')));if(stream)add(stream);add(enc((stream?'\nendstream\n':'\n')+'endobj\n'));};add(enc('%PDF-1.3\n%âãÏÓ\n'));imageObjs.forEach((o,i)=>{addObj(o.imgNo,`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${o.bytes.length} >>`,o.bytes);const content=enc(`q\n${width} 0 0 ${height} 0 0 cm\n/Im${i+1} Do\nQ\n`);addObj(o.contentNo,`<< /Length ${content.length} >>`,content);});pageNos.forEach((pno,i)=>addObj(pno,`<< /Type /Page /Parent ${pagesNo} 0 R /MediaBox [0 0 841.89 595.28] /Resources << /XObject << /Im${i+1} ${imageObjs[i].imgNo} 0 R >> >> /Contents ${imageObjs[i].contentNo} 0 R >>`));addObj(pagesNo,`<< /Type /Pages /Kids [${pageNos.map(n=>n+' 0 R').join(' ')}] /Count ${pageNos.length} >>`);addObj(catalogNo,`<< /Type /Catalog /Pages ${pagesNo} 0 R >>`);const xref=pos;add(enc('xref\n0 '+(catalogNo+1)+'\n0000000000 65535 f \n'));for(let i=1;i<=catalogNo;i++)add(enc(String(offsets[i]||0).padStart(10,'0')+' 00000 n \n'));add(enc(`trailer\n<< /Size ${catalogNo+1} /Root ${catalogNo} 0 R >>\nstartxref\n${xref}\n%%EOF`));const total=chunks.reduce((n,c)=>n+c.length,0),out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.length;}return new Blob([out],{type:'application/pdf'});}
async function exportPdf(){const key=state.activeMonth;if(!key||!state.claims[key]){showToast('Generate a claim first.');return}const rows=state.claims[key].rows.filter(r=>r.date);try{const [img1,img2]=await Promise.all([loadImage('template/page-1.jpg'),loadImage('template/page-2.jpg')]);const c1=document.createElement('canvas');c1.width=1404;c1.height=992;drawPage1(c1.getContext('2d'),img1,key);const jpegs=[canvasJpeg(c1)];const pageSize=18;for(let i=0;i<rows.length||i===0;i+=pageSize){const chunk=rows.slice(i,i+pageSize),c=document.createElement('canvas');c.width=1404;c.height=992;drawPage2(c.getContext('2d'),img2,chunk);jpegs.push(canvasJpeg(c));if(i+pageSize>=rows.length)break;}const blob=makeImagePdf(jpegs,1404,992);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Travel Claim - ${key}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);showToast(`PDF exported · ${jpegs.length} page${jpegs.length===1?'':'s'}`);}catch(e){console.error(e);window.print();showToast('PDF export failed; print/save as PDF has been opened instead.');}}
$('exportPdf').addEventListener('click',()=>exportPdf());
$('markSubmitted').addEventListener('click',()=>{const key=state.activeMonth;if(!key||!state.claims[key])return;if(state.expenseLog.some(x=>x.month===key)){showToast('This month is already in the expense log.');return}const rows=state.claims[key].rows,miles=rows.reduce((a,r)=>a+num(r.miles),0),misc=rows.reduce((a,r)=>a+num(r.miscAmount),0),totalMiles=miles*(Number(state.settings.mileageRate)||0.30),dates=rows.map(r=>new Date(r.date)).sort((a,b)=>a-b);state.expenseLog.push({id:'log-'+Date.now(),submitted:new Date().toISOString(),range:dates.length?`${dates[0].toLocaleDateString('en-GB')} - ${dates[dates.length-1].toLocaleDateString('en-GB')}`:monthLabel(key),miles,totalMiles,misc,total:totalMiles+misc,month:key});saveState();renderExpenseLog();showToast('Claim marked as submitted and added to the log.');});
function renderExpenseLog(){const body=$('logBody');body.innerHTML=state.expenseLog.map(x=>`<tr><td>${new Date(x.submitted).toLocaleDateString('en-GB')}</td><td>${escapeHtml(x.range)}</td><td>${money(x.totalMiles)}</td><td>${money(x.misc)}</td><td><b>${money(x.total)}</b></td><td><button class="log-delete" data-id="${escapeAttr(x.id)}">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" class="hint">No submitted claims yet.</td></tr>';const total=state.expenseLog.reduce((a,x)=>a+num(x.total),0);$('logTotal').textContent=money(total);qsa('.log-delete').forEach(b=>b.addEventListener('click',()=>{state.expenseLog=state.expenseLog.filter(x=>x.id!==b.dataset.id);saveState();renderExpenseLog();}));}
$('backupBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='travel-claims-manager-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
$('restoreInput').addEventListener('change',async()=>{const f=$('restoreInput').files[0];if(!f)return;try{state=mergeState(JSON.parse(await f.text()));bindSettings(true);$('icsUrl').value=state.icsUrl;$('proxySelect').value=state.proxy;renderAll();if(state.activeMonth)generateClaim(false);saveState();showToast('Backup restored.');}catch(e){showToast('Backup file could not be loaded.');}});
function renderAll(){renderMonths();renderShifts();renderClaimMonthOptions();renderExpenseLog();if(state.activeMonth)renderClaimHeader(state.activeMonth);}
// PWA install UI
const installBtn=$('installApp');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;installBtn.hidden=false;});installBtn.addEventListener('click',async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installBtn.hidden=true;}else if(/iphone|ipad|ipod/i.test(navigator.userAgent)){alert('In Safari: Share → Add to Home Screen → turn on Open as Web App → Add.');}});
window.addEventListener('appinstalled',()=>{installBtn.hidden=true;showToast('Travel Claims Manager installed.');});
bindSettings();renderAll();if(state.activeMonth&&state.claims[state.activeMonth])generateClaim(false);recoverFromCache();
})();
