const CACHE='pier-travel-expense-manager-v59';
const SHELL=['./','./index.html','./styles.css','./app.js','./app-parts/astral.js','./vendor/astral/main.js','./app-parts/app-00.js','./app-parts/app-01.js','./app-parts/app-02.js','./app-parts/app-03.js','./app-parts/app-04.js','./app-parts/app-05.js','./app-parts/app-06.js','./manifest.json','./icons/pier-logo-navy.png','./icons/pier-sunset-hero.jpg','./icons/android-add-home.png','./icons/favicon-32-v2.png','./icons/icon-192-v2.png','./icons/icon-512-v2.png','./template/page-1.jpg','./template/page-2.jpg','./icalendar-page-guide.jpg'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>(k.startsWith('travel-claims-manager-')||k.startsWith('pier-travel-expense-manager-'))&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;e.respondWith(fetch(e.request,{cache:'no-cache'}).then(r=>{if(r.ok){const copy=r.clone();e.waitUntil(caches.open(CACHE).then(c=>c.put(e.request,copy)));}return r;}).catch(async()=>await caches.match(e.request)||await caches.match(u.pathname.endsWith('/')?'./':'./index.html')));});
function openReminderDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open('travel-claims-reminders',1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('config'))db.createObjectStore('config');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function getReminderConfig(){const db=await openReminderDb();const values={};for(const key of ['installationId','deviceToken','workerUrl'])values[key]=await new Promise((resolve,reject)=>{const tx=db.transaction('config','readonly'),req=tx.objectStore('config').get(key);req.onsuccess=()=>resolve(req.result||'');req.onerror=()=>reject(req.error);});db.close();return values;}
async function pendingNotification(){const cfg=await getReminderConfig();if(!cfg.installationId||!cfg.deviceToken||!cfg.workerUrl)return null;const u=new URL('/api/push/pending',cfg.workerUrl);u.searchParams.set('installationId',cfg.installationId);const r=await fetch(u,{headers:{'X-Device-Token':cfg.deviceToken},cache:'no-store'});if(!r.ok)return null;return await r.json();}
self.addEventListener('push',event=>{event.waitUntil((async()=>{let n=null;try{n=await pendingNotification();}catch{}if(!n?.notification)n={notification:{title:'PIER',body:'Your travel claim needs attention.',target:'#shifts'}};const item=n.notification,tag=item.tag||'pier-travel-claim-reminder';await self.registration.showNotification(item.title||'PIER',{body:item.body||'Open PIER to review your travel claim.',icon:'icons/icon-192-v2.png',badge:'icons/icon-192-v2.png',tag,renotify:false,data:{url:item.target||'#shifts'}});const windows=await clients.matchAll({type:'window',includeUncontrolled:true});for(const client of windows)client.postMessage({type:'PIER_NOTIFICATION_SHOWN',tag});})());});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil((async()=>{const target=event.notification.data?.url||'#shifts',absolute=new URL(target,self.registration.scope).href,all=await clients.matchAll({type:'window',includeUncontrolled:true});for(const client of all){if(new URL(client.url).origin===new URL(self.registration.scope).origin){await client.focus();if('navigate' in client)await client.navigate(absolute);return;}}await clients.openWindow(absolute);})());});
