/**
 * Travel Claims Manager Worker v11
 * - POST /ics: privacy-conscious Allocate ICS fetcher.
 * - /api/push/*: optional Web Push + D1 reminder service.
 *
 * No claim rows, names, addresses, signatures, registration numbers or ICS URLs
 * are stored in D1. The reminder service stores only a random installation ID,
 * push subscription, reminder preferences and coarse monthly claim-state flags.
 */
const DEFAULT_ALLOWED_HOSTS=['nlag.allocate-cloud.co.uk'];
const DEFAULT_PUSH_HOSTS=['fcm.googleapis.com','updates.push.services.mozilla.com','push.services.mozilla.com','web.push.apple.com','wns2-am3p.notify.windows.com','notify.windows.com'];
const MAX_URL_LENGTH=4096,MAX_RESPONSE_BYTES=2*1024*1024,TIMEOUT_MS=15000,MAX_REDIRECTS=3;

function allowedHosts(env){const raw=String(env?.ALLOWED_HOSTS||'').trim();return raw?raw.split(',').map(v=>v.trim().toLowerCase()).filter(Boolean):DEFAULT_ALLOWED_HOSTS;}
function pushHosts(env){const raw=String(env?.PUSH_ALLOWED_HOSTS||'').trim();return raw?raw.split(',').map(v=>v.trim().toLowerCase()).filter(Boolean):DEFAULT_PUSH_HOSTS;}
function hostMatches(host,list){host=String(host||'').toLowerCase();return list.some(h=>host===h||host.endsWith('.'+h));}
function isAllowedHost(host,env){return hostMatches(host,allowedHosts(env));}
function isAllowedPushEndpoint(endpoint,env){try{const u=new URL(endpoint);return u.protocol==='https:'&&hostMatches(u.hostname,pushHosts(env));}catch{return false;}}
function originAllowed(request,env){const configured=String(env?.ALLOWED_ORIGIN||'*').trim(),origin=request.headers.get('Origin')||'';return configured==='*'||!origin||origin===configured;}
function corsHeaders(request,env){const configured=String(env?.ALLOWED_ORIGIN||'*').trim(),origin=request.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':configured==='*'?'*':(origin===configured?origin:configured),'Access-Control-Allow-Methods':'GET, POST, DELETE, OPTIONS','Access-Control-Allow-Headers':'Content-Type, X-Device-Token','Access-Control-Max-Age':'86400','Vary':'Origin'};}
function json(request,env,data,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(request,env),'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
function jsonError(request,env,status,message){return json(request,env,{ok:false,error:message},status);}
async function readJson(request){try{return await request.json();}catch{throw new Error('Request body must be JSON.');}}

async function upstream(url,signal){const c=new AbortController(),timer=setTimeout(()=>c.abort('timeout'),TIMEOUT_MS);if(signal){if(signal.aborted)c.abort(signal.reason);else signal.addEventListener('abort',()=>c.abort(signal.reason),{once:true});}try{return await fetch(url,{method:'GET',redirect:'manual',cache:'no-store',signal:c.signal,headers:{'Accept':'text/calendar,text/plain;q=0.9,*/*;q=0.1','User-Agent':'Travel-Claims-Manager-ICS-Worker/3.0'}});}finally{clearTimeout(timer);}}
async function fetchCalendar(raw,env,signal){let current=new URL(raw);if(current.protocol!=='https:')throw new Error('Only HTTPS calendar URLs are allowed.');if(!isAllowedHost(current.hostname,env))throw new Error(`Calendar host is not allowed: ${current.hostname}`);for(let n=0;n<=MAX_REDIRECTS;n++){const r=await upstream(current.toString(),signal);if(r.status>=300&&r.status<400){const loc=r.headers.get('Location');if(!loc)throw new Error('Calendar server returned a redirect without a destination.');current=new URL(loc,current);if(current.protocol!=='https:'||!isAllowedHost(current.hostname,env))throw new Error('Calendar redirect points to a host that is not allowed.');continue;}if(!r.ok)throw new Error(`Calendar server returned HTTP ${r.status}.`);const len=Number(r.headers.get('Content-Length')||0);if(len>MAX_RESPONSE_BYTES)throw new Error('Calendar response is larger than the 2 MB safety limit.');const text=await r.text();if(new TextEncoder().encode(text).byteLength>MAX_RESPONSE_BYTES)throw new Error('Calendar response is larger than the 2 MB safety limit.');if(!/BEGIN:VCALENDAR/i.test(text)||!/BEGIN:VEVENT/i.test(text))throw new Error('The requested URL did not return a readable ICS calendar.');return text;}throw new Error('Too many calendar redirects.');}

function b64urlBytes(bytes){let s='';for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function b64urlText(text){return b64urlBytes(new TextEncoder().encode(text));}
async function sha256Hex(text){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
async function authenticateInstallation(request,env,installationId){if(!env.DB)throw new Error('D1 is not configured.');const token=request.headers.get('X-Device-Token')||'';if(!installationId||!token)return false;const row=await env.DB.prepare('SELECT token_hash FROM installations WHERE installation_id = ?').bind(installationId).first();return !!row&&row.token_hash===await sha256Hex(token);}
function normalizePrefs(p={}){return {monthly:p.monthly!==false?1:0,deadline:p.deadline!==false?1:0,rota:p.rota!==false?1:0,unfinished:p.unfinished!==false?1:0,reminderTime:/^\d{2}:\d{2}$/.test(p.reminderTime||'')?p.reminderTime:'18:00',monthlyDay:Math.min(28,Math.max(1,Number(p.monthlyDay)||1)),deadlineDaysBefore:Math.min(4,Math.max(1,Number(p.deadlineDaysBefore)||3)),unfinishedDay:Math.min(28,Math.max(1,Number(p.unfinishedDay)||3)),deadlineToday:p.deadlineToday!==false?1:0};}
async function registerPush(request,env){if(!env.DB||!env.VAPID_PUBLIC_KEY||!env.VAPID_PRIVATE_JWK)return jsonError(request,env,503,'Push service is not configured.');const body=await readJson(request),installationId=String(body.installationId||''),deviceToken=String(body.deviceToken||''),sub=body.subscription||{},endpoint=String(sub.endpoint||'');if(!installationId||installationId.length>100||!deviceToken)return jsonError(request,env,400,'Missing installation credentials.');if(!isAllowedPushEndpoint(endpoint,env))return jsonError(request,env,400,'The browser returned an unsupported push-service endpoint.');const existing=await env.DB.prepare('SELECT token_hash FROM installations WHERE installation_id = ?').bind(installationId).first(),tokenHash=await sha256Hex(deviceToken);if(existing&&existing.token_hash!==tokenHash)return jsonError(request,env,403,'Installation credentials do not match.');const p=normalizePrefs(body.preferences),timezone=String(body.timezone||'Europe/London').slice(0,80);await env.DB.prepare(`INSERT INTO installations (installation_id,token_hash,endpoint,timezone,pref_monthly,pref_deadline,pref_rota,pref_unfinished,reminder_time,monthly_day,deadline_days_before,unfinished_day,deadline_today,updated_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)
ON CONFLICT(installation_id) DO UPDATE SET endpoint=excluded.endpoint,timezone=excluded.timezone,pref_monthly=excluded.pref_monthly,pref_deadline=excluded.pref_deadline,pref_rota=excluded.pref_rota,pref_unfinished=excluded.pref_unfinished,reminder_time=excluded.reminder_time,monthly_day=excluded.monthly_day,deadline_days_before=excluded.deadline_days_before,unfinished_day=excluded.unfinished_day,deadline_today=excluded.deadline_today,updated_at=CURRENT_TIMESTAMP`).bind(installationId,tokenHash,endpoint,timezone,p.monthly,p.deadline,p.rota,p.unfinished,p.reminderTime,p.monthlyDay,p.deadlineDaysBefore,p.unfinishedDay,p.deadlineToday).run();return json(request,env,{ok:true});}
async function updateClaimState(request,env){const body=await readJson(request),id=String(body.installationId||'');if(!await authenticateInstallation(request,env,id))return jsonError(request,env,403,'Installation authentication failed.');const months=Array.isArray(body.months)?body.months.slice(0,12):[];for(const m of months){if(!/^\d{4}-\d{2}$/.test(m.month||''))continue;await env.DB.prepare(`INSERT INTO claim_state (installation_id,month,has_shifts,claim_created,pdf_downloaded,submitted,needs_review_count,updated_at)
VALUES (?,?,?,?,?,?,?,CURRENT_TIMESTAMP)
ON CONFLICT(installation_id,month) DO UPDATE SET has_shifts=excluded.has_shifts,claim_created=excluded.claim_created,pdf_downloaded=excluded.pdf_downloaded,submitted=excluded.submitted,needs_review_count=excluded.needs_review_count,updated_at=CURRENT_TIMESTAMP`).bind(id,m.month,m.hasShifts?1:0,m.claimCreated?1:0,m.pdfDownloaded?1:0,m.submitted?1:0,Math.max(0,Number(m.needsReviewCount)||0)).run();}return json(request,env,{ok:true,months:months.length});}
async function removeSubscription(request,env){const body=await readJson(request),id=String(body.installationId||'');if(!await authenticateInstallation(request,env,id))return jsonError(request,env,403,'Installation authentication failed.');await env.DB.batch([env.DB.prepare('DELETE FROM pending_notifications WHERE installation_id=?').bind(id),env.DB.prepare('DELETE FROM claim_state WHERE installation_id=?').bind(id),env.DB.prepare('DELETE FROM notification_log WHERE installation_id=?').bind(id),env.DB.prepare('DELETE FROM installations WHERE installation_id=?').bind(id)]);return json(request,env,{ok:true});}
async function pendingNotification(request,env){const u=new URL(request.url),id=u.searchParams.get('installationId')||'';if(!await authenticateInstallation(request,env,id))return jsonError(request,env,403,'Installation authentication failed.');const row=await env.DB.prepare('SELECT title,body,target,tag FROM pending_notifications WHERE installation_id=?').bind(id).first();if(!row)return json(request,env,{ok:true,notification:null});await env.DB.prepare('DELETE FROM pending_notifications WHERE installation_id=?').bind(id).run();return json(request,env,{ok:true,notification:row});}

async function vapidJwt(endpoint,env){const audience=new URL(endpoint).origin,header=b64urlText(JSON.stringify({typ:'JWT',alg:'ES256'})),payload=b64urlText(JSON.stringify({aud:audience,exp:Math.floor(Date.now()/1000)+12*60*60,sub:String(env.VAPID_SUBJECT||'mailto:admin@example.invalid')})),unsigned=header+'.'+payload,jwk=JSON.parse(env.VAPID_PRIVATE_JWK),key=await crypto.subtle.importKey('jwk',jwk,{name:'ECDSA',namedCurve:'P-256'},false,['sign']),sig=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,new TextEncoder().encode(unsigned));return unsigned+'.'+b64urlBytes(sig);}
async function sendEmptyPush(inst,env){if(!isAllowedPushEndpoint(inst.endpoint,env))throw new Error('Stored push endpoint is not allowed.');const jwt=await vapidJwt(inst.endpoint,env),r=await fetch(inst.endpoint,{method:'POST',headers:{'Authorization':`vapid t=${jwt}, k=${env.VAPID_PUBLIC_KEY}`,'Crypto-Key':`p256ecdsa=${env.VAPID_PUBLIC_KEY}`,'TTL':'300','Urgency':'normal'},body:null});if(r.status===404||r.status===410){await env.DB.prepare('DELETE FROM installations WHERE installation_id=?').bind(inst.installation_id).run();return false;}if(!r.ok)throw new Error(`Push service returned HTTP ${r.status}`);return true;}
async function queueAndSend(inst,env,n){await env.DB.prepare(`INSERT INTO pending_notifications (installation_id,title,body,target,tag,created_at) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP)
ON CONFLICT(installation_id) DO UPDATE SET title=excluded.title,body=excluded.body,target=excluded.target,tag=excluded.tag,created_at=CURRENT_TIMESTAMP`).bind(inst.installation_id,n.title,n.body,n.target,n.tag||'travel-claims-reminder').run();return await sendEmptyPush(inst,env);}
async function testPush(request,env){const body=await readJson(request),id=String(body.installationId||'');if(!await authenticateInstallation(request,env,id))return jsonError(request,env,403,'Installation authentication failed.');const inst=await env.DB.prepare('SELECT * FROM installations WHERE installation_id=?').bind(id).first();try{await queueAndSend(inst,env,{title:'Travel Claims Manager test',body:'Notifications are working on this device.',target:'#shifts',tag:'travel-claims-test'});return json(request,env,{ok:true});}catch(e){return jsonError(request,env,502,e.message||'Push delivery failed.');}}

function localParts(date,tz){try{const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:tz||'Europe/London',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return {year:Number(parts.year),month:Number(parts.month),day:Number(parts.day),hour:Number(parts.hour)};}catch{return localParts(date,'Europe/London');}}
function previousMonth(y,m){if(m===1)return `${y-1}-12`;return `${y}-${String(m-1).padStart(2,'0')}`;}
function monthName(key){const [y,m]=key.split('-').map(Number);return new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,1)));}
async function alreadySent(env,id,kind,month,key){const row=await env.DB.prepare('SELECT 1 AS x FROM notification_log WHERE installation_id=? AND kind=? AND month=? AND dedupe_key=?').bind(id,kind,month,key).first();return !!row;}
async function logSent(env,id,kind,month,key){await env.DB.prepare('INSERT OR IGNORE INTO notification_log (installation_id,kind,month,dedupe_key,sent_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP)').bind(id,kind,month,key).run();}
async function maybeScheduled(inst,stateRow,kind,dateKey,month,n,env){if(await alreadySent(env,inst.installation_id,kind,month,dateKey))return;try{if(await queueAndSend(inst,env,n))await logSent(env,inst.installation_id,kind,month,dateKey);}catch(e){console.log('push failed',inst.installation_id,kind,String(e));}}
async function runScheduled(env){if(!env.DB||!env.VAPID_PUBLIC_KEY||!env.VAPID_PRIVATE_JWK)return;const all=await env.DB.prepare('SELECT * FROM installations LIMIT 500').all(),now=new Date();for(const inst of all.results||[]){const p=localParts(now,inst.timezone),hour=Number(String(inst.reminder_time||'18:00').split(':')[0]),dateKey=`${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')}`;if(p.hour!==hour)continue;const month=previousMonth(p.year,p.month),st=await env.DB.prepare('SELECT * FROM claim_state WHERE installation_id=? AND month=?').bind(inst.installation_id,month).first();if(!st||!st.has_shifts||st.submitted)continue;const label=monthName(month),review=Number(st.needs_review_count)||0;if(inst.pref_monthly&&p.day===Number(inst.monthly_day||1)){const n=review?{title:`${label} rota needs reviewing`,body:`${review} shift${review===1?'':'s'} need checking before your claim is created.`,target:`#shifts?month=${month}`,tag:`monthly-${month}`}:{title:`${label} travel claim is ready to review`,body:st.claim_created?'Your monthly claim has been started but is not marked submitted.':'Your rota is ready to review and create your travel claim.',target:st.claim_created?`#claim?month=${month}`:`#shifts?month=${month}`,tag:`monthly-${month}`};await maybeScheduled(inst,st,'monthly',dateKey,month,n,env);}if(inst.pref_unfinished&&p.day===Number(inst.unfinished_day||3)&&st.claim_created&&!st.submitted){const ready=!!st.pdf_downloaded,n={title:ready?`${label} claim is ready to submit`:`${label} travel claim is still in draft`,body:ready?'The PDF has been saved but the claim is not marked submitted.':'Open the claim form to finish your monthly claim.',target:`#claim?month=${month}`,tag:`unfinished-${month}`};await maybeScheduled(inst,st,'unfinished',dateKey,month,n,env);}if(inst.pref_deadline){const warningDay=Math.max(1,5-Number(inst.deadline_days_before||3));if(p.day===warningDay)await maybeScheduled(inst,st,'deadline-warning',dateKey,month,{title:`${label} travel claim deadline is approaching`,body:`Claims are due by the 5th. This claim is not marked as submitted.`,target:`#claim?month=${month}`,tag:`deadline-${month}`},env);if(inst.deadline_today&&p.day===5)await maybeScheduled(inst,st,'deadline-today',dateKey,month,{title:`${label} travel claim deadline is today`,body:'This claim is not marked as submitted.',target:`#claim?month=${month}`,tag:`deadline-${month}`},env);if(p.day===6)await maybeScheduled(inst,st,'overdue',dateKey,month,{title:`${label} travel claim is not marked submitted`,body:'The usual payroll deadline has passed. Open the claim to review its status.',target:`#claim?month=${month}`,tag:`overdue-${month}`},env);}}
}

export default {
 async fetch(request,env){
  if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(request,env)});
  if(!originAllowed(request,env))return jsonError(request,env,403,'This website origin is not allowed to use the Worker.');
  const url=new URL(request.url);
  if(url.pathname==='/ics'){
    if(request.method!=='POST')return jsonError(request,env,405,'Use POST /ics with a JSON body.');
    let body;try{body=await readJson(request);}catch(e){return jsonError(request,env,400,e.message);}
    const raw=String(body?.url||'').trim();if(!raw)return jsonError(request,env,400,'Missing calendar URL.');if(raw.length>MAX_URL_LENGTH)return jsonError(request,env,400,'Calendar URL is too long.');try{new URL(raw);}catch{return jsonError(request,env,400,'The calendar URL is not valid.');}
    try{const text=await fetchCalendar(raw,env,request.signal);return new Response(text,{status:200,headers:{...corsHeaders(request,env),'Content-Type':'text/calendar; charset=utf-8','Cache-Control':'no-store, private','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}});}catch(error){return jsonError(request,env,502,error?.name==='AbortError'?'Calendar request timed out.':(error?.message||'Unable to fetch calendar.'));}
  }
  if(url.pathname==='/api/push/config'&&request.method==='GET')return json(request,env,{ok:true,enabled:!!(env.DB&&env.VAPID_PUBLIC_KEY&&env.VAPID_PRIVATE_JWK),publicKey:env.VAPID_PUBLIC_KEY||''});
  try{
    if(url.pathname==='/api/push/register'&&request.method==='POST')return await registerPush(request,env);
    if(url.pathname==='/api/push/state'&&request.method==='POST')return await updateClaimState(request,env);
    if(url.pathname==='/api/push/subscription'&&request.method==='DELETE')return await removeSubscription(request,env);
    if(url.pathname==='/api/push/pending'&&request.method==='GET')return await pendingNotification(request,env);
    if(url.pathname==='/api/push/test'&&request.method==='POST')return await testPush(request,env);
  }catch(e){return jsonError(request,env,500,e.message||'Notification service error.');}
  return new Response('Travel Claims Manager Worker is running.',{status:200,headers:{...corsHeaders(request,env),'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}});
 },
 async scheduled(controller,env,ctx){ctx.waitUntil(runScheduled(env));}
};
