'use strict';
function onStackRowEdit(e){const el=e.target,key=el.dataset.month,r=state.claims[key]?.rows?.[Number(el.dataset.row)],k=el.dataset.field;if(!r)return;if(k==='date'){const [d,m]=el.value.split('/');if(d&&m)r.date=new Date(Number(key.slice(0,4)),Number(m)-1,Number(d));}else if(k==='start'||k==='end'){const [h,mi]=el.value.split(':').map(Number),base=new Date(r.date);if(Number.isFinite(h)){base.setHours(h||0,mi||0,0,0);r[k]=base;}}else if(['miles','passengerMiles','miscAmount','mealAmount'].includes(k))r[k]=el.value===''?'':Number(el.value);else r[k]=el.value;saveState();}
function blankRow(month){const [y,m]=String(month||state.activeMonth||monthKey(new Date())).split('-').map(Number),now=new Date(y,m-1,1,9,0),base=BASES[state.settings.baseSite]||{postcode:''},home=getPostcode(state.settings.homeAddress);return{id:'manual-row-'+Date.now(),claimType:'R',date:now,start:now,end:now,detail:'',from:home,to:base.postcode,miles:'',passengerMiles:'',miscLabel:'',miscAmount:'',mealFrom:'',mealTo:'',mealAmount:''};}
function isHomeboundRow(row){return /^\s*home\s*bound\b/i.test(String(row?.detail||''));}
rowHtml=(r,i,key,editing)=>{const cell=(field,val,type='text')=>`<input class="row-input" data-month="${key}" data-row="${i}" data-field="${field}" type="${type}" value="${escapeAttr(val??'')}">`;return `<tr class="${isHomeboundRow(r)?'homebound-row':''}"><td>${editing?cell('date',displayDate(r.date)):displayDate(r.date)}</td><td>${claimTypeCell(r,i,key,editing)}</td><td>${editing?cell('start',parseTimeFromDate(r.start),'time'):parseTimeFromDate(r.start)}</td><td>${editing?cell('detail',r.detail):escapeHtml(r.detail)}</td><td>${editing?cell('end',parseTimeFromDate(r.end),'time'):parseTimeFromDate(r.end)}</td><td>${editing?cell('from',r.from):escapeHtml(r.from)}</td><td>${editing?cell('to',r.to):escapeHtml(r.to)}</td><td>${editing?cell('miles',r.miles??'','number'):fmtNum(r.miles)}</td><td>${editing?cell('passengerMiles',r.passengerMiles??'','number'):fmtNum(r.passengerMiles)}</td><td>${editing?cell('miscLabel',r.miscLabel||''):escapeHtml(r.miscLabel||'')}</td><td>${editing?cell('miscAmount',r.miscAmount??'','number'):money(r.miscAmount)}</td><td>${editing?cell('mealFrom',r.mealFrom||'','time'):escapeHtml(r.mealFrom||'')}</td><td>${editing?cell('mealTo',r.mealTo||'','time'):escapeHtml(r.mealTo||'')}</td><td>${editing?cell('mealAmount',r.mealAmount??'','number'):money(r.mealAmount)}</td>${editing?`<td><button class="row-delete" data-month="${key}" data-row="${i}" type="button">Delete</button></td>`:''}</tr>`;};
const renderClaimsStackBase=renderClaimsStack;
renderClaimsStack=function(){renderClaimsStackBase();qsa('.stack-claim-table').forEach(table=>{Array.from(table.tHead?.rows?.[0]?.cells||[]).forEach(cell=>{cell.innerHTML=cell.innerHTML.replace(/^\[2\]\s*/,'');});const miscHeading=table.tHead?.rows?.[1]?.cells?.[9];if(miscHeading)miscHeading.innerHTML=miscColumnHeadingHtml();const label=table.tFoot?.rows?.[0]?.cells?.[0];if(label){label.textContent='TOTAL';label.classList.add('preview-total-label');}});};
function generateClaim(force=false){const key=state.activeMonth;if(!key)return;const previous=state.claims[key]||{};const rows=!force&&previous.rows?.length?previous.rows:makeClaimRows(key);state.claims[key]={...previous,rows,generatedAt:Date.now(),exportedAt:force?null:previous.exportedAt||null};renderClaimsStack();saveState();}
function regenerateSelectedClaims(){const months=state.selectedMonths.slice().sort();if(!months.length){showToast('Select at least one claim month first.');return}if(!confirm('Regenerate all selected claim contents? This replaces edits made directly in the claim tables.'))return;for(const key of months){const previous=state.claims[key]||{};state.claims[key]={...previous,rows:makeClaimRows(key),generatedAt:Date.now(),exportedAt:null,signedDate:''};editingMonths.delete(key);if(typeof recordClaimMetric==='function')recordClaimMetric(key,true);}state.activeMonth=months[0];renderClaimsStack();saveState();showToast(`${months.length} claim${months.length===1?'':'s'} regenerated from Setup and shifts.`);}
$('regenerateClaims')?.addEventListener('click',regenerateSelectedClaims);
let drawing=false,signatureDrawn=false,last={x:0,y:0};const canvas=$('signaturePad'),ctx=canvas.getContext('2d');ctx.lineWidth=2;ctx.lineCap='round';function pos(e){const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*(canvas.width/r.width),y:(p.clientY-r.top)*(canvas.height/r.height)}}function start(e){drawing=true;last=pos(e)}function move(e){if(!drawing)return;const p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();signatureDrawn=true;last=p;e.preventDefault()}function stop(){drawing=false}canvas.addEventListener('mousedown',start);canvas.addEventListener('mousemove',move);canvas.addEventListener('mouseup',stop);canvas.addEventListener('mouseleave',stop);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',stop);$('setupSignature').addEventListener('click',()=>{$('signatureDialog').showModal()});$('closeSig').addEventListener('click',()=>$('signatureDialog').close());$('clearSig').addEventListener('click',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signatureDrawn=false;});$('saveSig').addEventListener('click',()=>{if(!signatureDrawn){showToast('Please draw your signature first.');return}state.signature=canvas.toDataURL('image/png');state.signatureDate='';$('signatureDialog').close();if($('claimsStack'))renderClaimsStack();updateWorkflowHints();saveState();showToast('Sample signature saved locally.');});
async function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Could not load PDF template'));im.src=src;});}
function wrapText(ctx,text,maxWidth){const words=String(text??'').split(/\s+/);const lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test;}if(line)lines.push(line);return lines;}
function drawTextFit(ctx,text,x,y,maxWidth,maxFont=14,minFont=7){let size=maxFont;ctx.font=size+'px Arial';while(size>minFont&&ctx.measureText(String(text??'')).width>maxWidth){size--;ctx.font=size+'px Arial';}ctx.fillText(String(text??''),x,y);return size;}
function drawWrappedTextFit(ctx,text,x,y,maxWidth,maxLines=2,maxFont=12,minFont=7,lineHeight=9){let size=maxFont,lines=[];while(size>=minFont){ctx.font=size+'px Arial';lines=wrapText(ctx,text,maxWidth);if(lines.length<=maxLines)break;size-=.5;}lines.slice(0,maxLines).forEach((line,index)=>ctx.fillText(line,x,y+(index-(Math.min(lines.length,maxLines)-1)/2)*lineHeight));return size;}
function drawPage1(ctx,img,key){ctx.drawImage(img,0,0,1404,992);ctx.fillStyle='#fff';ctx.fillRect(938,121,192,31);ctx.strokeStyle='#111';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(944,145);ctx.lineTo(1114,145);ctx.stroke();ctx.fillRect(1005,203,150,31);ctx.beginPath();ctx.moveTo(1010,226);ctx.lineTo(1140,226);ctx.stroke();ctx.fillStyle='#000';ctx.textBaseline='alphabetic';const dataFont=18,dataMin=11;drawTextFit(ctx,state.settings.fullName,318,139,300,dataFont,dataMin);drawTextFit(ctx,monthLabel(key),944,136,166,dataFont,dataMin);drawTextFit(ctx,state.settings.baseSite,318,181,300,dataFont,dataMin);drawTextFit(ctx,state.settings.designation,318,224,300,dataFont,dataMin);drawTextFit(ctx,formatPersonalNumber(state.settings.personalNumber),1010,218,126,dataFont,dataMin);const addr=formatAddressLines(state.settings.homeAddress);addr.forEach((line,i)=>drawTextFit(ctx,line,318,261+i*20,300,dataFont,dataMin));drawTextFit(ctx,String(state.settings.vehicleReg||'').toUpperCase(),1010,262,130,dataFont,dataMin);drawTextFit(ctx,state.settings.engineCc,875,307,125,dataFont,dataMin);if(state.signature){const sig=new Image();sig.src=state.signature;ctx.drawImage(sig,318,620,250,36);}const signedDate=state.claims[key]?.signedDate||state.signatureDate||'';if(signedDate){drawTextFit(ctx,signedDate,872,663,190,dataFont,dataMin);}}
function redrawStartTimeHeader(ctx){ctx.save();ctx.fillStyle='#fff';ctx.fillRect(153,25,58,88);ctx.fillStyle='#111';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='11px Arial';ctx.fillText('START',182,53);ctx.font='12px Arial';ctx.fillText('TIME',182,80);ctx.restore();}
function redrawMiscHeader(ctx){const lines=miscColumnHeadingLines();ctx.save();ctx.fillStyle='#fff';ctx.fillRect(920,55,168,58);ctx.fillStyle='#111';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='10px Arial';const lineHeight=14,start=84-(Math.max(1,lines.length)-1)*lineHeight/2;lines.forEach((line,index)=>ctx.fillText(line,1004,start+index*lineHeight));ctx.restore();}
function drawFinalPageLegend(ctx,img,tableBottom){const sourceY=752,sourceHeight=216,legendY=Math.min(752,tableBottom+36);ctx.fillStyle='#fff';ctx.fillRect(0,tableBottom+24,1404,944-(tableBottom+24));ctx.drawImage(img,0,sourceY,1375,sourceHeight,0,legendY,1375,sourceHeight);ctx.fillStyle='#fff';ctx.fillRect(1375,legendY,29,sourceHeight);}
function drawLegendOnlyPage(ctx,img){ctx.fillStyle='#fff';ctx.fillRect(0,0,1404,992);ctx.drawImage(img,0,752,1375,216,0,80,1375,216);ctx.fillStyle='#fff';ctx.fillRect(1375,80,29,216);}
function drawPage2(ctx,img,rows,claimTotals=null,showLegend=false){
  ctx.drawImage(img,0,0,1404,992);redrawStartTimeHeader(ctx);redrawMiscHeader(ctx);
  ctx.fillStyle='#fff';ctx.fillRect(0,752,1404,240);
  const bodyTop=114,rowH=28,x=[28,93,152,212,512,571,665,760,819,919,1089,1166,1224,1283,1375],bottom=bodyTop+rowH*rows.length;
  ctx.fillStyle='#fff';ctx.fillRect(28,bodyTop,1347,638);
  rows.forEach((r,i)=>{if(isHomeboundRow(r)){ctx.fillStyle='#eeeeee';ctx.fillRect(28,bodyTop+i*rowH,1347,rowH);}});
  ctx.strokeStyle='#111';ctx.lineWidth=1;ctx.beginPath();for(const xx of x){ctx.moveTo(xx,bodyTop);ctx.lineTo(xx,bottom)}for(let i=0;i<=rows.length;i++){const yy=bodyTop+i*rowH;ctx.moveTo(28,yy);ctx.lineTo(1375,yy)}ctx.stroke();
  ctx.fillStyle='#111';ctx.textAlign='center';ctx.textBaseline='middle';
  rows.forEach((r,i)=>{const y=bodyTop+i*rowH+rowH/2;drawTextFit(ctx,displayDate(r.date),60,y,54,16,10);drawTextFit(ctx,r.claimType||'R',122,y,52,16,10);drawTextFit(ctx,parseTimeFromDate(r.start),182,y,52,16,10);drawWrappedTextFit(ctx,r.detail,362,y,286,2,15,9,12);drawTextFit(ctx,parseTimeFromDate(r.end),541,y,52,16,10);drawTextFit(ctx,r.from||'',618,y,86,15,9);drawTextFit(ctx,r.to||'',712,y,86,15,9);drawTextFit(ctx,fmtNum(r.miles),789,y,52,16,10);drawTextFit(ctx,fmtNum(r.passengerMiles),869,y,92,16,9);drawWrappedTextFit(ctx,r.miscLabel||'',1004,y,160,2,14.5,8,11);drawTextFit(ctx,r.miscAmount?Number(r.miscAmount).toFixed(2):'',1127,y,69,16,9);drawTextFit(ctx,r.mealFrom||'',1195,y,50,15,9);drawTextFit(ctx,r.mealTo||'',1253,y,50,15,9);drawTextFit(ctx,r.mealAmount?Number(r.mealAmount).toFixed(2):'',1329,y,82,16,9);});
  if(!claimTotals)return;
  ctx.fillStyle='#fff';ctx.fillRect(512,bottom,863,rowH);ctx.strokeStyle='#111';ctx.strokeRect(512,bottom,248,rowH);ctx.strokeRect(760,bottom,59,rowH);ctx.strokeRect(819,bottom,100,rowH);ctx.strokeRect(919,bottom,170,rowH);ctx.strokeRect(1089,bottom,77,rowH);ctx.strokeRect(1166,bottom,117,rowH);ctx.strokeRect(1283,bottom,92,rowH);
  ctx.fillStyle='#111';ctx.font='bold 15px Arial';ctx.textAlign='center';ctx.fillText('TOTAL',636,bottom+rowH/2);ctx.fillText(fmtNum(claimTotals.miles),789,bottom+rowH/2);ctx.fillText(fmtNum(claimTotals.pass),869,bottom+rowH/2);ctx.fillText('TOTAL',1004,bottom+rowH/2);ctx.fillText(money(claimTotals.misc).replace('£',''),1127,bottom+rowH/2);ctx.fillText('TOTAL',1224,bottom+rowH/2);ctx.fillText(money(claimTotals.meals).replace('£',''),1329,bottom+rowH/2);
  if(showLegend)drawFinalPageLegend(ctx,img,bottom);
}
function drawPageNumber(ctx,page,total){ctx.save();ctx.fillStyle='#111';ctx.textAlign='center';ctx.textBaseline='alphabetic';ctx.font='12px Arial';ctx.fillText(`${page} of ${total}`,702,974);ctx.restore();}
function canvasJpeg(canvas){return canvas.toDataURL('image/jpeg',0.9).split(',')[1];}
function base64Bytes(b64){const bin=atob(b64),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out;}
function makeImagePdf(jpegs,width,height){const imageObjs=[];let objNo=1;for(const b64 of jpegs){imageObjs.push({imgNo:objNo++,contentNo:objNo++,bytes:base64Bytes(b64)});}const pageNos=imageObjs.map(()=>objNo++),pagesNo=objNo++,catalogNo=objNo++;const chunks=[],offsets=[0];let pos=0;const enc=s=>new TextEncoder().encode(s);const add=bytes=>{chunks.push(bytes);pos+=bytes.length;};const addObj=(no,body,stream)=>{offsets[no]=pos;add(enc(no+' 0 obj\n'+body+(stream?'\nstream\n':'')));if(stream)add(stream);add(enc((stream?'\nendstream\n':'\n')+'endobj\n'));};add(enc('%PDF-1.3\n%âãÏÓ\n'));imageObjs.forEach((o,i)=>{addObj(o.imgNo,`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${o.bytes.length} >>`,o.bytes);const content=enc(`q\n841.89 0 0 595.28 0 0 cm\n/Im${i+1} Do\nQ\n`);addObj(o.contentNo,`<< /Length ${content.length} >>`,content);});pageNos.forEach((pno,i)=>addObj(pno,`<< /Type /Page /Parent ${pagesNo} 0 R /MediaBox [0 0 841.89 595.28] /Resources << /XObject << /Im${i+1} ${imageObjs[i].imgNo} 0 R >> >> /Contents ${imageObjs[i].contentNo} 0 R >>`));addObj(pagesNo,`<< /Type /Pages /Kids [${pageNos.map(n=>n+' 0 R').join(' ')}] /Count ${pageNos.length} >>`);addObj(catalogNo,`<< /Type /Catalog /Pages ${pagesNo} 0 R >>`);const xref=pos;add(enc('xref\n0 '+(catalogNo+1)+'\n0000000000 65535 f \n'));for(let i=1;i<=catalogNo;i++)add(enc(String(offsets[i]||0).padStart(10,'0')+' 00000 n \n'));add(enc(`trailer\n<< /Size ${catalogNo+1} /Root ${catalogNo} 0 R >>\nstartxref\n${xref}\n%%EOF`));const total=chunks.reduce((n,c)=>n+c.length,0),out=new Uint8Array(total);let off=0;for(const c of chunks){out.set(c,off);off+=c.length;}return new Blob([out],{type:'application/pdf'});}
function claimPdfFilename(key){const parts=String(state.settings.fullName||'').trim().split(/\s+/).filter(Boolean),initial=(parts[0]?.[0]||'').toUpperCase(),surname=parts.at(-1)||'',person=[initial,surname].filter(Boolean).join(' ').replace(/[<>:"/\\|?*]+/g,'').trim();return `Travel Claim${person?' - '+person:''} - ${key}.pdf`;}
function paginateClaimRows(rows){const intermediatePageSize=29,finalPageSize=28,legendPageSize=21,chunks=[];let offset=0;while(rows.length-offset>finalPageSize){const remaining=rows.length-offset,size=Math.min(intermediatePageSize,Math.max(1,remaining-1));chunks.push(rows.slice(offset,offset+size));offset+=size;}chunks.push(rows.slice(offset));chunks.legendSeparate=(chunks.at(-1)?.length||0)>legendPageSize;return chunks;}
async function exportPdfForMonth(key){if(!state.signature)throw new Error('Sample signature is missing.');if(!state.claims[key])state.claims[key]={rows:makeClaimRows(key),generatedAt:Date.now()};state.claims[key].signedDate=new Date().toLocaleDateString('en-GB');const rows=state.claims[key].rows.filter(r=>r.date),claimTotals=totalsFor(rows),chunks=paginateClaimRows(rows),separateLegend=!!chunks.legendSeparate;const [img1,img2]=await Promise.all([loadImage('template/page-1.jpg'),loadImage('template/page-2.jpg')]),totalPages=1+chunks.length+(separateLegend?1:0),c1=document.createElement('canvas');c1.width=1404;c1.height=992;drawPage1(c1.getContext('2d'),img1,key);drawPageNumber(c1.getContext('2d'),1,totalPages);const jpegs=[canvasJpeg(c1)];chunks.forEach((chunk,index)=>{const c=document.createElement('canvas'),isLast=index===chunks.length-1,showLegend=isLast&&!separateLegend;c.width=1404;c.height=992;drawPage2(c.getContext('2d'),img2,chunk,isLast?claimTotals:null,showLegend);drawPageNumber(c.getContext('2d'),index+2,totalPages);jpegs.push(canvasJpeg(c));});if(separateLegend){const c=document.createElement('canvas');c.width=1404;c.height=992;drawLegendOnlyPage(c.getContext('2d'),img2);drawPageNumber(c.getContext('2d'),totalPages,totalPages);jpegs.push(canvasJpeg(c));}const blob=makeImagePdf(jpegs,1404,992),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=claimPdfFilename(key);document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500);state.claims[key].exportedAt=new Date().toISOString();addExpenseLogForMonth(key);saveState();return jpegs.length;}
function addExpenseLogForMonth(key){if(state.expenseLog.some(x=>x.month===key))return;const rows=state.claims[key]?.rows||[],miles=rows.reduce((a,r)=>a+num(r.miles),0),misc=rows.reduce((a,r)=>a+num(r.miscAmount),0),totalMiles=miles*(Number(state.settings.mileageRate)||0.30),dates=rows.map(r=>new Date(r.date)).sort((a,b)=>a-b);state.expenseLog.push({id:'log-'+Date.now()+'-'+key,submitted:new Date().toISOString(),range:dates.length?`${dates[0].toLocaleDateString('en-GB')} - ${dates[dates.length-1].toLocaleDateString('en-GB')}`:monthLabel(key),miles,totalMiles,misc,total:totalMiles+misc,month:key});}
let lastPdfSessionMonths=[];
$('signAndSaveSelected').addEventListener('click',async()=>{if(!validateSetup())return;const checks=qsa('.save-month-check:checked').map(x=>x.dataset.month).sort();if(!checks.length){showToast('Select at least one month to save.');return}const btn=$('signAndSaveSelected');try{btn.disabled=true;lastPdfSessionMonths=[];for(const key of checks){await exportPdfForMonth(key);lastPdfSessionMonths.push(key);}renderClaimsStack();renderExpenseLog();updateWorkflowHints();showToast(`${checks.length} PDF${checks.length===1?'':'s'} saved.`);}catch(e){console.error(e);showToast(e.message||'PDF export failed.');}finally{btn.disabled=false;}});
$('humberBridge').addEventListener('click',()=>{if(state.settings.commuteType==='humber'||state.settings.otherExpenseType==='humber')window.open('https://toll.humberbridge.co.uk/','_blank','noopener');});
function naturalJoin(items){if(items.length<2)return items[0]||'';if(items.length===2)return `${items[0]} and ${items[1]}`;return `${items.slice(0,-1).join(', ')} and ${items.at(-1)}`;}
function monthsPhrase(months){const valid=Array.from(new Set(months)).filter(m=>/^\d{4}-\d{2}$/.test(m)).sort(),groups=[];for(const key of valid){const [year,month]=key.split('-').map(Number);let group=groups.at(-1);if(!group||group.year!==year){group={year,names:[]};groups.push(group);}group.names.push(new Date(year,month-1,1).toLocaleDateString(undefined,{month:'long'}));}const phrases=groups.map(group=>`${naturalJoin(group.names)} ${group.year}`);if(phrases.length<2)return phrases[0]||'';return `${phrases.slice(0,-1).join(', ')}, and ${phrases.at(-1)}`;}
function payrollProofAttachments(sessionMonths){const rows=sessionMonths.flatMap(key=>state.claims[key]?.rows||[]),labels=rows.map(row=>String(row.miscLabel||'').toLowerCase()),types=[state.settings.commuteType,state.settings.otherExpenseType].filter(Boolean),hasToll=types.includes('humber')||labels.some(label=>/humber|toll/.test(label)),hasParking=types.includes('parking')||labels.some(label=>/parking/.test(label)),hasAdditional=types.some(type=>!['none','humber','parking'].includes(type))||rows.some(row=>num(row.miscAmount)>0&&!/humber|toll|parking/i.test(String(row.miscLabel||''))),proof=[];if(hasToll)proof.push('proof of toll crossings');if(hasParking)proof.push('proof of parking');if(hasAdditional)proof.push('proof of additional expenses');return proof;}
$('emailPayroll').addEventListener('click',()=>{const parts=String(state.settings.fullName||'').trim().split(/\s+/),surname=parts.at(-1)||'',first=parts[0]||'',sessionMonths=lastPdfSessionMonths.length?lastPdfSessionMonths:state.selectedMonths.slice().sort(),months=monthsPhrase(sessionMonths)||monthLabel(state.activeMonth),count=Math.max(1,sessionMonths.length),formWord=count===1?'form':'forms',attachments=naturalJoin([`completed travel expenses ${formWord}`,...payrollProofAttachments(sessionMonths)]),subject=`${surname} - Travel expenses for ${months}`,body=`Payroll assignment no.: ${state.settings.personalNumber}\n\nDear Payroll,\n\nPlease find ${attachments} attached. These cover ${months}.\n\nRegards\n\n${first} ${surname}\n${state.settings.designation}`;location.href=`mailto:nlg-tr.payrollenquiries@nhs.net?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;});
function renderExpenseLog(){const body=$('logBody');body.innerHTML=state.expenseLog.map(x=>`<tr><td>${new Date(x.submitted).toLocaleDateString('en-GB')}</td><td>${escapeHtml(x.range)}</td><td>${money(x.totalMiles)}</td><td>${money(x.misc)}</td><td><b>${money(x.total)}</b></td><td><button class="log-delete" data-id="${escapeAttr(x.id)}">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" class="hint">No submitted claims yet.</td></tr>';const total=state.expenseLog.reduce((a,x)=>a+num(x.total),0);$('logTotal').textContent=money(total);qsa('.log-delete').forEach(b=>b.addEventListener('click',()=>{state.expenseLog=state.expenseLog.filter(x=>x.id!==b.dataset.id);saveState();renderExpenseLog();}));}
$('backupBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='travel-claims-manager-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
$('restoreInput').addEventListener('change',async()=>{const f=$('restoreInput').files[0];if(!f)return;try{state=mergeState(JSON.parse(await f.text()));bindSettings(true);bindReminderSettings(true);$('icsUrl').value=state.icsUrl;renderAll();if(state.activeMonth)generateClaim(false);saveState();showToast('Backup restored.');}catch(e){showToast('Backup file could not be loaded.');}});
function renderCalendarSource(){const label=$('calendarSourceLabel'),panel=$('localIcsPanel'),status=$('icsFileStatus');if(panel)panel.hidden=!!state.icsUrl;if(state.icsUrl){if(label)label.textContent='The saved calendar link refreshes automatically whenever Shifts opens.';}else if(state.usingExampleData){if(label)label.textContent=`Using ${state.events.length} synthetic testing shifts for ${monthLabel(state.selectedMonths[0]||monthKey(new Date()))}.`;if(status)status.textContent='Example testing data is active. Choose a local ICS file to replace it.';}else if(state.icsFileUpdatedAt){const updated=new Date(state.icsFileUpdatedAt).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'});if(label)label.textContent=`Using a local ICS file last updated ${updated}. Import a new file whenever the rota changes.`;if(status)status.textContent=`Last updated ${updated}. This file does not refresh automatically.`;}else{if(label)label.textContent='No iCalendar link is saved. Import an ICS file below or return to Setup to add a link.';if(status)status.textContent='This option is fully local. Imported files must be updated manually.';}}
function renderAll(){renderMonths();renderShifts();renderExpenseLog();renderCalendarSource();if($('claimsStack'))renderClaimsStack();updateWorkflowHints();}
const installBtn=$('installApp');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;installBtn.hidden=false;});installBtn.addEventListener('click',async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installBtn.hidden=true;}else if(/iphone|ipad|ipod/i.test(navigator.userAgent)){alert('In Safari: Share → Add to Home Screen → turn on Open as Web App → Add.');}});
window.addEventListener('appinstalled',()=>{installBtn.hidden=true;showToast('Travel Claims Manager installed.');});
bindSettings();bindReminderSettings();renderAll();{const r=parseRouteHash();switchTab(r.tab,r.month);}if(state.activeMonth&&state.claims[state.activeMonth])generateClaim(false);recoverFromCache();
if('serviceWorker' in navigator&&(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1')){let reloadingForUpdate=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloadingForUpdate)return;reloadingForUpdate=true;location.reload();});navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>{});}
