'use strict';
function reminderConfigured(){const r=state.reminders||DEFAULT_STATE.reminders;return !!(r.calendarEnabled||r.pushEnabled);}
function updateNotificationBell(){const r=state.reminders||DEFAULT_STATE.reminders,button=$('openNotifications');if(!button)return;const configured=reminderConfigured(),forbidden=!!r.pushFailed||(!configured&&!!r.notificationPromptReviewed);button.classList.toggle('needs-attention',forbidden);button.classList.toggle('is-active',configured&&!r.pushFailed);const message=r.pushFailed?'Notifications need attention: '+(r.pushFailureMessage||'a push notification failed.'):(forbidden?'Notifications are not configured.':'Notification settings');button.title=message;button.setAttribute('aria-label',message);if($('notificationDialogStatus'))$('notificationDialogStatus').textContent=r.pushFailed?'Push notification problem: '+(r.pushFailureMessage||'delivery failed.'):(configured?'A reminder is configured.':'Choose a reminder type.');}
function updatePushUi(){const r=state.reminders||DEFAULT_STATE.reminders,status=$('pushStatus'),feedback=$('pushFeedback'),test=$('testPush'),disable=$('disablePush'),enable=$('enablePush');if(status)status.textContent=r.pushFailed?'Notification problem':(r.pushEnabled&&r.calendarEnabled?'Calendar and push enabled ✓':r.pushEnabled?'Push enabled ✓':r.calendarEnabled?'Calendar reminder saved ✓':'No reminder configured');if(test)test.disabled=!r.pushEnabled;if(disable)disable.hidden=!r.pushEnabled;if(enable)enable.textContent=r.pushEnabled?'Update push subscription':'Enable push notifications';if(feedback){if(r.pushFailed)feedback.textContent=`Push notifications need attention: ${r.pushFailureMessage||'a notification could not be delivered.'} Review the settings and enable or test push again.`;else if(r.pushEnabled)feedback.textContent='Push reminders are enabled for this device. Notification details are kept generic; claim data remains local.';}updateNotificationBell();}
function markPushFailure(error){const r=ensureReminderIdentity();r.pushFailed=true;r.pushFailureMessage=String(error?.message||error||'A push notification failed.').slice(0,240);r.notificationPromptReviewed=true;saveState();updatePushUi();return error;}
function clearPushFailure(){const r=ensureReminderIdentity();r.pushFailed=false;r.pushFailureMessage='';r.notificationPromptReviewed=true;updatePushUi();saveState();}
function b64urlToBytes(value){const s=value.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(value.length/4)*4,'=');const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}function bytesToB64url(value){let s='';for(const b of new Uint8Array(value))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function reminderApi(path,init={}){const headers={'Content-Type':'application/json',...(init.headers||{})};const res=await fetch(BAKED_WORKER_URL.replace(/\/+$/,'')+path,{cache:'no-store',...init,headers});let data={};try{data=await res.json();}catch{}if(!res.ok)throw new Error(data.error||`Reminder service returned HTTP ${res.status}.`);return data;}
async function getAppServiceWorker(){if(!('serviceWorker' in navigator))throw new Error('This browser does not support service workers.');if(!(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'))throw new Error('Push notifications require the hosted HTTPS version of Travel Claims Manager.');let reg=await navigator.serviceWorker.getRegistration();if(!reg)reg=await navigator.serviceWorker.register('sw.js');await navigator.serviceWorker.ready;return reg;}
function reminderDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open('travel-claims-reminders',1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('config'))db.createObjectStore('config');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function saveSwReminderConfig(){const r=ensureReminderIdentity(),db=await reminderDb();await new Promise((resolve,reject)=>{const tx=db.transaction('config','readwrite'),st=tx.objectStore('config');st.put(r.installationId,'installationId');st.put(r.deviceToken,'deviceToken');st.put(BAKED_WORKER_URL,'workerUrl');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
function pushPrefs(){const r=state.reminders;return {monthly:!!r.pushMonthly,deadline:!!r.pushDeadline,rota:!!r.pushRota,unfinished:!!r.pushUnfinished,reminderTime:r.pushReminderTime||'18:00',monthlyDay:1,deadlineDaysBefore:Number(r.pushDeadlineDays)||3,unfinishedDay:Number(r.pushUnfinishedDay)||3,deadlineToday:false};}
async function refreshPushHealth(){const r=ensureReminderIdentity();if(!r.pushEnabled)return;try{const data=await reminderApi(`/api/push/status?installationId=${encodeURIComponent(r.installationId)}`,{method:'GET',headers:{'X-Device-Token':r.deviceToken}});r.pushFailed=!!data.failed;r.pushFailureMessage=data.message||'';updatePushUi();saveState();if(r.pushFailed)showToast('A push notification failed. Review notification settings.');}catch(error){markPushFailure(error);}}
async function syncPushRegistration(){const r=ensureReminderIdentity();if(!r.pushEnabled)return;const reg=await getAppServiceWorker(),sub=await reg.pushManager.getSubscription();if(!sub){r.pushEnabled=false;throw markPushFailure(new Error('The browser push subscription is missing. Enable push notifications again.'));}await saveSwReminderConfig();await reminderApi('/api/push/register',{method:'POST',body:JSON.stringify({installationId:r.installationId,deviceToken:r.deviceToken,subscription:sub.toJSON(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/London',preferences:pushPrefs()})});clearPushFailure();queuePushStateSync(true);}
async function enablePushNotifications(){const feedback=$('pushFeedback');try{const ios=/iphone|ipad|ipod/i.test(navigator.userAgent),installed=window.matchMedia('(display-mode: standalone)').matches;if(ios&&!installed)throw new Error('On iPhone or iPad: open this page in Safari, tap Share → Add to Home Screen, then open the installed Travel Claims app and enable notifications there.');if(!('Notification' in window)||!('PushManager' in window))throw new Error('Push notifications are unavailable in this browser. Try the installed app or use the monthly calendar reminder instead.');if(Notification.permission==='denied')throw new Error(/android/i.test(navigator.userAgent)?'Notifications are blocked. In Chrome, open this site’s settings, choose Permissions → Notifications → Allow, then try again.':'Notifications are blocked for this site. Allow them in the browser or device settings, then try again.');const config=await reminderApi('/api/push/config',{method:'GET',headers:{}});if(!config.enabled)throw new Error('The notification service is not configured yet. Complete the D1/VAPID steps in the included setup guide.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notifications were not enabled. You can use the monthly calendar reminder instead, or allow notifications in this site’s settings and try again.');const reg=await getAppServiceWorker();let sub=await reg.pushManager.getSubscription();if(sub?.options?.applicationServerKey&&bytesToB64url(sub.options.applicationServerKey)!==config.publicKey){await sub.unsubscribe();sub=null;}if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64urlToBytes(config.publicKey)});ensureReminderIdentity();state.reminders.pushEnabled=true;await saveSwReminderConfig();await reminderApi('/api/push/register',{method:'POST',body:JSON.stringify({installationId:state.reminders.installationId,deviceToken:state.reminders.deviceToken,subscription:sub.toJSON(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/London',preferences:pushPrefs()})});clearPushFailure();queuePushStateSync(true);updatePushUi();feedback.textContent='Push notifications enabled. Use “Send test notification” to check delivery.';showToast('Push notifications enabled.');}catch(e){markPushFailure(e);if(feedback)feedback.textContent=e.message||'Could not enable push notifications.';showToast(e.message||'Could not enable push notifications.');}}
async function disablePushNotifications(){const feedback=$('pushFeedback');try{const r=ensureReminderIdentity();try{await reminderApi('/api/push/subscription',{method:'DELETE',headers:{'X-Device-Token':r.deviceToken},body:JSON.stringify({installationId:r.installationId})});}catch{}const reg=await navigator.serviceWorker?.getRegistration();const sub=await reg?.pushManager?.getSubscription();if(sub)await sub.unsubscribe();r.pushEnabled=false;r.pushFailed=false;r.pushFailureMessage='';r.notificationPromptReviewed=true;saveState();updatePushUi();if(feedback)feedback.textContent='Push notifications are disabled on this device.';showToast('Push notifications disabled.');}catch(e){markPushFailure(e);showToast(e.message||'Could not disable push notifications.');}}
let pushStateTimer=null;
function queuePushStateSync(immediate=false){if(!state.reminders?.pushEnabled)return;clearTimeout(pushStateTimer);pushStateTimer=setTimeout(()=>syncPushState().catch(markPushFailure),immediate?50:1800);}
function monthPushState(key){const items=allEventItems().filter(e=>monthKey(e.start)===key),claim=state.claims[key]||{},submitted=state.expenseLog.some(x=>x.month===key);return {month:key,hasShifts:items.length>0,claimCreated:Array.isArray(claim.rows)&&claim.rows.length>0,pdfDownloaded:!!claim.exportedAt,submitted,needsReviewCount:items.filter(e=>e.category==='study').length};}

'use strict';
async function syncPushState(){const r=state.reminders;if(!r?.pushEnabled)return;const months=Array.from(new Set([...claimWindowMonths(),...state.selectedMonths])).sort();await reminderApi('/api/push/state',{method:'POST',headers:{'X-Device-Token':r.deviceToken},body:JSON.stringify({installationId:r.installationId,months:months.map(monthPushState)})});}
let lastPushTestAt=0;
async function sendTestPush(){const feedback=$('pushFeedback'),button=$('testPush'),now=Date.now();if(now-lastPushTestAt<60000){const wait=Math.ceil((60000-(now-lastPushTestAt))/1000),message=`Please wait ${wait} seconds before sending another test notification.`;if(feedback)feedback.textContent=message;showToast(message);return}let listener;try{lastPushTestAt=now;if(button)button.disabled=true;const r=ensureReminderIdentity(),tag='pier-notification-test';await syncPushState();let resolveDelivery;const delivered=new Promise(resolve=>{resolveDelivery=resolve;setTimeout(()=>resolve(false),12000);});listener=event=>{if(event.data?.type==='PIER_NOTIFICATION_SHOWN'&&event.data.tag===tag)resolveDelivery(true);};navigator.serviceWorker.addEventListener('message',listener);await reminderApi('/api/push/test',{method:'POST',headers:{'X-Device-Token':r.deviceToken},body:JSON.stringify({installationId:r.installationId})});const confirmed=await delivered;clearPushFailure();if(feedback)feedback.textContent=confirmed?'Test notification delivered successfully.':'The test was sent, but Android has not confirmed display yet. PIER will not create a duplicate fallback notification.';showToast(confirmed?'Test notification delivered.':'Test notification sent.');}catch(e){markPushFailure(e);if(feedback)feedback.textContent=e.message||'Test notification failed.';showToast(e.message||'Test notification failed.');}finally{if(listener)navigator.serviceWorker.removeEventListener('message',listener);if(button)button.disabled=!state.reminders?.pushEnabled;}}
function icsEscape(v){return String(v||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');}
function nextMonthlyOccurrence(day,time){const [h,m]=String(time||'17:00').split(':').map(Number),now=new Date(),d=new Date(now.getFullYear(),now.getMonth(),Math.min(5,Math.max(1,Number(day)||1)),h||0,m||0,0,0);if(d<=now)d.setMonth(d.getMonth()+1);return d;}
function icsLocalDateTime(d){return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}${String(d.getMinutes()).padStart(2,'0')}00`;}
function saveCalendarReminder(){const r=state.reminders,day=Math.min(5,Math.max(1,Number(r.calendarDay)||1)),start=nextMonthlyOccurrence(day,r.calendarTime),end=new Date(start.getTime()+30*60000),appUrl=location.protocol==='https:'?(location.origin+location.pathname+'#shifts'):'https://pier.bynour.uk/#shifts',uid=`pier-travel-reminder-${day}@pier.bynour.uk`,description=`Payroll's deadline for claims, to be paid end of this month, is on the 5th of the month\nopen PIER Travel Expense Manager: ${appUrl}`,eventLocation='💰🌳Magic money tree in the garden of that delightful person who "pays your wages💰"',ics=['BEGIN:VCALENDAR','VERSION:2.0','CALSCALE:GREGORIAN','PRODID:-//Travel Claims Manager//Monthly Reminder//EN','BEGIN:VTIMEZONE','TZID:Europe/London','X-LIC-LOCATION:Europe/London','BEGIN:DAYLIGHT','TZOFFSETFROM:+0000','TZOFFSETTO:+0100','TZNAME:BST','DTSTART:19700329T010000','RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU','END:DAYLIGHT','BEGIN:STANDARD','TZOFFSETFROM:+0100','TZOFFSETTO:+0000','TZNAME:GMT','DTSTART:19701025T020000','RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU','END:STANDARD','END:VTIMEZONE','BEGIN:VEVENT',`UID:${uid}`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;TZID=Europe/London:${icsLocalDateTime(start)}`,`DTEND;TZID=Europe/London:${icsLocalDateTime(end)}`,'RRULE:FREQ=MONTHLY;INTERVAL=1',`SUMMARY:${icsEscape('💸 Travel claim deadline reminder 💸')}`,`DESCRIPTION:${icsEscape(description)}`,`LOCATION:${icsEscape(eventLocation)}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='PIER Travel Expense Manager - monthly reminder.ics';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);r.calendarEnabled=true;r.notificationPromptReviewed=true;saveState();updatePushUi();showToast('Monthly calendar reminder created. It repeats until you delete it from your calendar.');}
async function maybeNotifyRotaChange(diff){if(!state.reminders?.pushEnabled||!state.reminders.pushRota||!('Notification' in window)||Notification.permission!=='granted')return;if(!(diff.added||diff.changed||diff.removed))return;try{const reg=await getAppServiceWorker(),parts=[];if(diff.changed)parts.push(`${diff.changed} changed`);if(diff.added)parts.push(`${diff.added} added`);if(diff.removed)parts.push(`${diff.removed} removed`);const month=(diff.affectedMonths||[]).sort()[0]||monthKey(new Date());await reg.showNotification('Your rota has changed',{body:`${parts.join(', ')}. Review the affected shifts before claiming.`,icon:'icons/icon-192-v2.png',badge:'icons/icon-192-v2.png',tag:'rota-change-'+month,data:{url:routeFor('shifts',month)}});clearPushFailure();}catch(error){markPushFailure(error);}}
$('saveCalendarReminder')?.addEventListener('click',saveCalendarReminder);
$('enablePush')?.addEventListener('click',enablePushNotifications);
$('testPush')?.addEventListener('click',sendTestPush);
$('disablePush')?.addEventListener('click',disablePushNotifications);

function normalizeUrl(url){let u=String(url||'').trim();if(u.startsWith('webcal://'))u='https://'+u.slice(9);return u;}
function unfoldICS(text){const lines=text.replace(/\r\n/g,'\n').replace(/\r/g,'\n').split('\n');const out=[];for(const line of lines){if(/^[ \t]/.test(line)&&out.length)out[out.length-1]+=line.slice(1);else out.push(line);}return out;}
function unescapeText(s){return String(s??'').replace(/\\n/g,'\n').replace(/\\,/g,',').replace(/\\;/g,';').replace(/\\\\/g,'\\');}
function icsDate(v){if(!v)return null;let s=String(v).replace(/^.*?:/,'');if(/^\d{8}$/.test(s))return new Date(Number(s.slice(0,4)),Number(s.slice(4,6))-1,Number(s.slice(6,8)),9,0,0);const z=s.endsWith('Z');if(z)s=s.slice(0,-1);const y=+s.slice(0,4),mo=+s.slice(4,6)-1,d=+s.slice(6,8),h=+(s.slice(9,11)||0),mi=+(s.slice(11,13)||0),sec=+(s.slice(13,15)||0);return z?new Date(Date.UTC(y,mo,d,h,mi,sec)):new Date(y,mo,d,h,mi,sec);}
function parseCalendarFallback(text){const lines=unfoldICS(text),events=[];let cur=null;for(const line of lines){if(line==='BEGIN:VEVENT'){cur={};continue}if(line==='END:VEVENT'){if(cur?.dtstart)events.push(cur);cur=null;continue}if(!cur)continue;const m=line.match(/^([A-Z0-9-]+)(?:;[^:]*)?:(.*)$/);if(m)cur[m[1].toLowerCase()]=m[2];}
return expandSimpleRecurrence(events.map((e,i)=>({uid:e.uid||'fallback-'+i,summary:unescapeText(e.summary||'Shift'),description:unescapeText(e.description||''),start:icsDate(e.dtstart),end:icsDate(e.dtend||e.dtstart),allDay:(e.dtstart||'').length===8,rrule:e.rrule||'',exdate:e.exdate||''})).filter(e=>e.start));}
function expandSimpleRecurrence(events){const out=[];const limit=new Date(Date.now()+1000*60*60*24*366*3);for(const e of events){const duration=(e.end?.getTime()||e.start.getTime()+3600000)-e.start.getTime();const rule=e.rrule||'';if(!rule){out.push(e);continue}const parts={};rule.split(';').forEach(x=>{const [k,v]=x.split('=');parts[k]=v});const freq=parts.FREQ;let interval=Number(parts.INTERVAL||1),count=Number(parts.COUNT||0),until=parts.UNTIL?icsDate(parts.UNTIL):null;let cur=new Date(e.start),n=0;while(cur<=limit&&(until?cur<=until:true)&&(count? n<count:true)){out.push({...e,uid:e.uid+'-'+n,start:new Date(cur),end:new Date(cur.getTime()+duration)});n++;if(freq==='DAILY')cur.setDate(cur.getDate()+interval);else if(freq==='WEEKLY')cur.setDate(cur.getDate()+7*interval);else if(freq==='MONTHLY')cur.setMonth(cur.getMonth()+interval);else break} }return out;}

'use strict';
function classifyEvent(e){const s=(e.summary+' '+(e.description||'')).toLowerCase();if(/study|\bsdt\b/.test(s))return {status:'Do not claim',category:'study'};if(/leave|annual|holiday|a\/l|maternity|mat\s*-?leave|bereav|sick|sickness|strike|\bphc\b|healthcare|appointment/.test(s))return {status:'Do not claim',category:'leave'};return {status:'Claim',category:'work'};}
async function fetchWithTimeout(url,ms=15000,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',redirect:'error',signal:c.signal,...init});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text();}finally{clearTimeout(timer);}}
function isIcs(text){return /BEGIN:VCALENDAR/i.test(text)&&/BEGIN:VEVENT/i.test(text);}
async function fetchText(url){const u=normalizeUrl(url);let last=null;try{const text=await fetchWithTimeout(BAKED_WORKER_URL.replace(/\/+$/,'')+'/ics',15000,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:u})});if(isIcs(text))return {text,source:'Travel Claims secure Worker'};last=new Error('Worker returned a response that was not an ICS calendar.');}catch(e){last=e;}try{const text=await fetchWithTimeout(u);if(isIcs(text))return {text,source:'Direct calendar'};last=new Error('Direct calendar response was not ICS.');}catch(e){last=e;}throw last||new Error('Unable to fetch calendar. You can import an .ics file instead.');}
function claimWindowMonths(){const out=[],now=new Date();for(let i=3;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);out.push(monthKey(d));}return out;}
function eventFingerprint(e){return [e.summary||'',new Date(e.start).toISOString(),new Date(e.end||e.start).toISOString()].join('|');}
function applyCalendarText(text,source){const parsed=parseCalendarFallback(text);if(!parsed.length)throw new Error('No calendar events were found.');const oldByUid=new Map(state.events.map(e=>[e.uid,e]));const next=parsed.map((e,i)=>{const c=classifyEvent(e),old=oldByUid.get(e.uid);return {...e,id:e.uid+'-'+i,status:old?.status||c.status,category:c.category,source};});const nextByUid=new Map(next.map(e=>[e.uid,e]));let added=0,removed=0,changed=0;const affected=new Set();for(const [uid,e] of nextByUid){const old=oldByUid.get(uid);if(!old){added++;affected.add(monthKey(e.start));}else if(eventFingerprint(old)!==eventFingerprint(e)){changed++;affected.add(monthKey(e.start));affected.add(monthKey(old.start));}}for(const [uid,old] of oldByUid)if(!nextByUid.has(uid)){removed++;affected.add(monthKey(old.start));}state.events=next;const allowed=new Set(claimWindowMonths());state.selectedMonths=state.selectedMonths.filter(m=>allowed.has(m));renderAll();saveState();return {added,removed,changed,affectedMonths:Array.from(affected).filter(Boolean)};}
let calendarLoading=false;
async function loadIcs(automatic=false){if(calendarLoading)return;state.icsUrl=$('icsUrl').value.trim();state.workerUrl=BAKED_WORKER_URL;saveState();const feedback=$('calendarFeedback');if(!state.icsUrl){feedback.className='calendar-feedback error';feedback.textContent='No ICS calendar URL is saved. Go back to Setup and paste your Allocate calendar link.';return}calendarLoading=true;$('icsState').textContent='Refreshing calendar…';feedback.className='calendar-feedback loading';feedback.textContent='Refreshing your saved calendar automatically…';try{const result=await fetchText(state.icsUrl);const diff=applyCalendarText(result.text,result.source);$('icsState').textContent=`${state.events.length} events loaded · ${result.source}`;const summary=[];if(diff.changed)summary.push(`${diff.changed} shift${diff.changed===1?'':'s'} changed`);if(diff.added)summary.push(`${diff.added} shift${diff.added===1?'':'s'} added`);if(diff.removed)summary.push(`${diff.removed} shift${diff.removed===1?'':'s'} removed`);feedback.className='calendar-feedback success';feedback.textContent=summary.length?`Calendar refreshed. ${summary.join(', ')}.`:'Calendar refreshed. No rota changes detected since the last fetch.';if(summary.length)maybeNotifyRotaChange(diff);if(!automatic)showToast('Calendar refreshed.');}catch(e){if(typeof recordCalendarAttempt==='function')recordCalendarAttempt(false,'Calendar URL',e);const msg=e.name==='AbortError'?'Calendar request timed out.':(e.message||'Could not fetch calendar.');$('icsState').textContent='Calendar refresh failed';feedback.className='calendar-feedback error';feedback.textContent=`Automatic calendar refresh failed: ${msg} You can still import an .ics file directly below.`;}finally{calendarLoading=false;}}
async function loadIcsFile(file){if(!file)return;const feedback=$('calendarFeedback');feedback.className='calendar-feedback loading';feedback.textContent='Reading the ICS file locally…';try{const text=await file.text();if(!isIcs(text))throw new Error('The selected file does not look like an ICS calendar.');state.icsUrl='';state.icsFileUpdatedAt=new Date(Number(file.lastModified)||Date.now()).toISOString();state.usingExampleData=false;if($('icsUrl'))$('icsUrl').value='';applyCalendarText(text,'Local file');$('icsState').textContent=state.events.length+' events loaded · Local file';feedback.className='calendar-feedback success';feedback.textContent=`ICS file imported successfully: ${state.events.length} events. Remember to import an updated file when the rota changes.`;renderCalendarSource();closeDialog?.('calendarHelpDialog');showToast('ICS file imported locally.');}catch(e){if(typeof recordCalendarAttempt==='function')recordCalendarAttempt(false,'Local file',e);$('icsState').textContent='ICS file load failed';feedback.className='calendar-feedback error';feedback.textContent=e.message||'Could not read the ICS file.';showToast(e.message||'Could not read the ICS file.');}}
$('icsFile').addEventListener('change',e=>loadIcsFile(e.target.files[0]));
$('calendarHelpFile')?.addEventListener('change',e=>loadIcsFile(e.target.files[0]));
function allEventItems(){return [...state.events,...state.manualEvents];}
function renderMonths(){const months=claimWindowMonths();$('monthPicker').className='month-picker';$('monthPicker').innerHTML=months.map(m=>{const count=allEventItems().filter(e=>monthKey(e.start)===m).length;return `<label class="month-chip"><input type="checkbox" data-month="${m}" ${state.selectedMonths.includes(m)?'checked':''}>${monthLabel(m)}<span class="month-count">${count} imported shift${count===1?'':'s'}</span></label>`}).join('');qsa('#monthPicker input').forEach(i=>i.addEventListener('change',()=>{state.selectedMonths=qsa('#monthPicker input:checked').map(x=>x.dataset.month);renderShifts();if($('claimsStack'))renderClaimsStack();updateWorkflowHints();saveState();}));updateWorkflowHints();}
