const $=id=>document.getElementById(id),money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}),number=new Intl.NumberFormat('en-GB');
let channel='live',page=1,limit=20,sort='last_seen_at',direction='desc',selected=new Set();
const metricDefinitions={
  'Unique users · 3 months':'Pseudonymous installations active in the selected environment during the last three months.',
  'New users · 30 days':'Installations first seen during the last 30 days.',
  'Returning users':'Percentage of active installations first seen more than 30 days ago.',
  'Calendar imports successful':'Successful attempts as a percentage of all calendar-import attempts.',
  'Calendar imports failed':'Failed attempts as a percentage of all calendar-import attempts.',
  'ICS file share':'Percentage of successful calendar imports made from a local ICS file rather than a live link.',
  'Shifts imported per claim':'Average imported shifts for each claim month created.',
  'Shifts edited per claim':'Average recorded shift or claim-row edits for each claim month created.',
  'Shifts added per claim':'Average manually added shifts for each claim month created.',
  'Imported shifts edited':'Recorded shift or claim-row edits as a percentage of imported shifts.',
  'Average time to first PDF':'Average time from first use to the first saved claim PDF.',
  'Unique claims created':'Distinct claim months created within each installation, added together.',
  'Unique PDFs exported':'Distinct claim months saved as PDFs within each installation, added together.',
  'Humber Bridge clicks':'Number of times the Humber Bridge information action was selected.',
  'Email payroll clicks':'Number of times the Email payroll action was selected.',
  'Claimed · 3 months':'Aggregate claimed amount recorded over the last three months; it is not an audited payment total.',
  'Miles · 3 months':'Aggregate claimable mileage recorded over the last three months.',
  'Push failures':'Push-notification registrations currently marked as failed.'
};
const reliabilityDefinitions={network:'The calendar could not be reached or returned a network or HTTP error.',timeout:'The calendar request did not finish within the allowed time.','invalid-calendar':'The content was empty or not recognised as readable ICS calendar data.','file-read':'A local ICS file could not be read.',unknown:'The import failed but did not match a known cause.'};
const reliabilityLabels={network:'Network',timeout:'Timeout','invalid-calendar':'Invalid calendar','file-read':'File read',unknown:'Unknown'};
const journeyDefinitions={opened:'PIER was opened, but no later workflow stage has yet been recorded.',calendar:'A calendar was imported, but the user did not progress to shift review.',shifts:'The user reached shift review, but did not progress to the claim form.',claim:'The user reached or created a claim form, but did not progress to a PDF or the Expense Log.',pdf:'The user saved a PDF, but has not subsequently opened the Expense Log.',log:'The user opened the Expense Log; this is the final recorded stage.'};
const journeyLabels={opened:'Opened',calendar:'Calendar',shifts:'Shifts',claim:'Claim',pdf:'PDF',log:'Log'};
async function api(path,init){const r=await fetch(path,{cache:'no-store',...init}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Dashboard request failed');return d}
function el(tag,value='',cls){const n=document.createElement(tag);n.textContent=value;if(cls)n.className=cls;return n}
function query(){return new URLSearchParams({channel,page,limit,sort,direction,q:$('search').value,device:$('device').value,status:$('recordStatus').value})}
function percent(part,total){return total?Math.round(Number(part||0)*100/total)+'%':'—'}
function minutes(value){const amount=Number(value||0);if(!amount)return '—';if(amount<60)return number.format(amount)+' min';return (amount/60).toFixed(1)+' hr'}
function cards(d){const imports=Number(d.calendarImportSuccesses||0)+Number(d.calendarImportFailures||0),successfulSources=Number(d.icsFileImports||0)+Number(d.icsUrlImports||0),claims=Number(d.claimsCreated||0),perClaim=value=>claims?(Number(value||0)/claims).toFixed(1):'—',rows=[['Unique users · 3 months',number.format(d.uniqueUsers||0)],['New users · 30 days',number.format(d.newUsers||0)],['Returning users',percent(d.returningUsers,d.uniqueUsers)],['Calendar imports successful',percent(d.calendarImportSuccesses,imports)],['Calendar imports failed',percent(d.calendarImportFailures,imports)],['ICS file share',percent(d.icsFileImports,successfulSources)],['Shifts imported per claim',perClaim(d.shiftsImported)],['Shifts edited per claim',perClaim(d.shiftsEdited)],['Shifts added per claim',perClaim(d.shiftsAdded)],['Imported shifts edited',percent(d.shiftsEdited,d.shiftsImported)],['Average time to first PDF',minutes(d.averageTimeToFirstPdfMinutes)],['Unique claims created',number.format(d.claimsCreated||0)],['Unique PDFs exported',number.format(d.pdfsCreated||0)],['Humber Bridge clicks',number.format(d.humberClicks||0)],['Email payroll clicks',number.format(d.payrollEmailClicks||0)],['Claimed · 3 months',money.format(Number(d.claimedLastThreeMonthsPence||0)/100)],['Miles · 3 months',number.format(Number(d.milesLastThreeMonthsTenths||0)/10)],['Push failures',number.format(d.pushFailures||0)]];$('cards').replaceChildren(...rows.map(([label,value])=>{const card=el('div','','card');card.tabIndex=0;card.dataset.tooltip=metricDefinitions[label];card.setAttribute('aria-label',`${label}. ${value}. ${metricDefinitions[label]}`);card.append(el('strong',value),el('span',label));return card}))}
function list(id,items,empty='No data yet.'){$(id).replaceChildren(...(items.length?items:[[empty,'',null]]).map(([label,value,definition])=>{const item=el('li',value===''?label:`${label}: ${number.format(value)}`);if(definition){item.tabIndex=0;item.dataset.tooltip=definition;item.setAttribute('aria-label',`${label}: ${number.format(value)}. ${definition}`);}return item}));}
function renderRows(rows,total){const body=$('telemetryRows');body.replaceChildren();for(const x of rows){const tr=document.createElement('tr'),check=document.createElement('input');check.type='checkbox';check.dataset.installationId=x.installation_id;check.checked=selected.has(x.installation_id);check.addEventListener('change',()=>{check.checked?selected.add(x.installation_id):selected.delete(x.installation_id);updateSelection()});const cells=[x.installation_id,new Date(x.last_seen_at+'Z').toLocaleString('en-GB'),x.device_type,x.app_version,money.format(x.claimed_last_3_months_pence/100),number.format(x.claims_created)+' / '+number.format(x.pdfs_created),x.funnel_stage||'opened'];const selectionCell=el('td','');selectionCell.append(check);tr.append(selectionCell);for(const v of cells)tr.append(el('td',v));tr.append(el('td',x.excluded_from_aggregates?'Removed':'Included','pill'+(x.excluded_from_aggregates?' removed':'')));const actions=el('td','');const remove=el('button',x.excluded_from_aggregates?'Restore':'Remove','secondary');remove.onclick=()=>exclude([x.installation_id],!x.excluded_from_aggregates);const del=el('button','Delete','danger');del.onclick=()=>removeRows([x.installation_id]);actions.append(remove,del);tr.append(actions);body.append(tr)}$('selectPage').checked=rows.length>0&&rows.every(x=>selected.has(x.installation_id));$('pageStatus').textContent=`Page ${page} · ${number.format(total)} records`;$('prevPage').disabled=page===1;$('nextPage').disabled=page*limit>=total;updateSelection()}
function updateSelection(){const n=selected.size;$('selectionStatus').textContent=n?`${n} selected`:'No records selected';for(const id of ['bulkRemove','bulkRestore','bulkDelete'])$(id).disabled=!n}
async function load(){try{$('status').hidden=false;const d=await api('/api/dashboard/data?'+query());cards(d);list('failures',Object.entries(d.failureReasons||{}).map(([key,value])=>[reliabilityLabels[key]||key,value,reliabilityDefinitions[key]||'Calendar-import failures recorded under this cause.']),'No calendar-import failures recorded.');list('funnel',(d.funnel||[]).map(x=>[journeyLabels[x.label]||x.label,x.value,journeyDefinitions[x.label]||'Furthest recorded workflow stage.']),'No journey stages recorded.');renderRows(d.telemetry||[],d.telemetryTotal||0);renderReports(d.reports||[]);setEditor(await api('/api/dashboard/config?channel='+channel));$('content').hidden=false;$('status').hidden=true}catch(e){$('status').hidden=false;$('status').textContent=e.message}}
async function exclude(ids,excluded){try{let changed=0;for(const installationId of ids){const result=await api('/api/dashboard/telemetry/exclusion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,installationId,excluded})});changed+=Number(result.changed)||0}selected.clear();$('status').hidden=false;$('status').textContent=changed?`${changed} record${changed===1?'':'s'} ${excluded?'removed from totals':'restored to totals'}.`:'No matching telemetry records were changed.';await load()}catch(error){$('status').hidden=false;$('status').textContent=error.message}}
async function removeRows(ids){if(!confirm(`Permanently delete ${ids.length} selected telemetry record${ids.length===1?'':'s'} and suppress future records from those installations?`))return;for(const id of ids)await api('/api/dashboard/telemetry/'+channel+'/'+encodeURIComponent(id),{method:'DELETE'});selected.clear();load()}
function renderReports(items){const root=$('reports');root.replaceChildren(...(items.length?items:[{description:'No reports are currently retained.'}]).map(x=>{const a=el('article','', 'report');a.append(el('strong',x.report_id||'No reports'),el('p',x.description));if(x.created_at)a.append(el('small',new Date(x.created_at+'Z').toLocaleString('en-GB')));return a}))}
function setEditor(d){const f=$('editor'),c=d.config?.colours||{},t=d.config?.text||{};for(const x of f.querySelectorAll('input[type=color]'))x.value=c[x.name]||'#123047';for(const x of f.querySelectorAll('input:not([type=color]),textarea'))x.value=t[x.name]||''}
function draft(){const f=new FormData($('editor')),colours={},text={};for(const k of ['deepNavy','steelBlue','sunsetCopper','duneGold','warmBackground','cardWhite'])colours[k]=f.get(k);for(const k of ['tabSetup','tabShifts','tabClaim','tabLog','helpBody','aboutBody','privacyBody'])text[k]=String(f.get(k)||'').trim();return {channel,config:{colours,text}}}
async function save(msg='Draft saved.'){await api('/api/dashboard/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft())});$('editorStatus').textContent=msg}
document.querySelectorAll('[data-channel]').forEach(b=>b.onclick=()=>{channel=b.dataset.channel;page=1;selected.clear();$('content').dataset.channel=channel;document.querySelector('.environment').dataset.channel=channel;document.querySelectorAll('[data-channel]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));load()});document.querySelector('.environment').dataset.channel='live';document.querySelector('[data-channel=live]').setAttribute('aria-pressed','true');document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const s=b.dataset.sort;direction=s===sort&&direction==='desc'?'asc':'desc';sort=s;page=1;load()});for(const id of ['search','device','recordStatus','pageSize'])$(id).onchange=()=>{limit=+$('pageSize').value;page=1;load()};$('selectPage').onchange=e=>{document.querySelectorAll('#telemetryRows input[type=checkbox]').forEach(x=>e.target.checked?selected.add(x.dataset.installationId):selected.delete(x.dataset.installationId));updateSelection()};$('bulkRemove').onclick=()=>exclude([...selected],true);$('bulkRestore').onclick=()=>exclude([...selected],false);$('bulkDelete').onclick=()=>removeRows([...selected]);$('prevPage').onclick=()=>{page--;load()};$('nextPage').onclick=()=>{page++;load()};$('refresh').onclick=load;$('editor').onsubmit=e=>{e.preventDefault();save()};$('publishDraft').onclick=async()=>{if(confirm(`Publish the saved draft to ${channel}?`)){await save('Publishing…');await api('/api/dashboard/config/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel})});$('editorStatus').textContent='Published.'}};$('undoLive').onclick=()=>api('/api/dashboard/config/undo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel})}).then(()=>load());$('previewDraft').onclick=async()=>{await save();window.open((channel==='live'?'https://pier.bynour.uk/':'https://beta.pier.bynour.uk/')+'?pier_preview=1','_blank','noopener')};$('telemetryDefinitions').onclick=()=>$('telemetryDefinitionsDialog').showModal();$('telemetryDefinitionsClose').onclick=()=>$('telemetryDefinitionsDialog').close();load();
